"""Extended built-in POI data merged into CITY_DEFAULTS.

Coordinates are approximate: city center plus a deterministic jitter so VRP
gets non-zero transit times without requiring an external geocoder.
"""

from __future__ import annotations

import hashlib

from schemas import Location, ScoredPOI


def _jitter(name: str, lat: float, lng: float) -> Location:
    """Return a deterministic but slightly jittered location."""
    h = int(hashlib.sha256(name.encode("utf-8")).hexdigest(), 16)
    dlat = ((h % 200) - 100) / 1000.0  # ±0.10°
    dlng = (((h // 200) % 200) - 100) / 1000.0
    return Location(lat=round(lat + dlat, 5), lng=round(lng + dlng, 5))


CITY_CENTERS = {
    "上海": (31.2304, 121.4737),
    "北京": (39.9042, 116.4074),
    "广州": (23.1291, 113.2644),
    "成都": (30.5728, 104.0668),
    "杭州": (30.2741, 120.1551),
    "西安": (34.3416, 108.9398),
    "重庆": (29.5630, 106.5516),
    "深圳": (22.5431, 114.0579),
    "南京": (32.0603, 118.7969),
    "厦门": (24.4798, 118.0894),
    "青岛": (36.0671, 120.3826),
}


def _poi(city: str, name: str, category: str, **kwargs) -> ScoredPOI:
    """Build a ScoredPOI with sensible defaults and jittered coordinates."""
    lat, lng = CITY_CENTERS[city]
    defaults = {
        "score": 0.8,
        "description": kwargs.get("description", name),
        "tags": [],
        "ticket_price": 0,
        "best_time": "全天",
        "recommended_hours": "2小时",
        "area": city,
        "indoor_outdoor": "outdoor",
        "location": _jitter(name, lat, lng),
        "data_source": "built_in",
        "confidence": 0.8,
        "is_fallback": True,
        "fallback_reason": "built-in extended fallback data",
    }
    defaults.update(kwargs)
    defaults["name"] = name
    defaults["category"] = category
    return ScoredPOI(**defaults)


CITY_EXTRA: dict[str, list[ScoredPOI]] = {
    "上海": [
        _poi(
            "上海",
            "上海野生动物园",
            "attraction",
            description="国家级野生动物园，适合亲子",
            tags=["亲子", "动物", "户外"],
            recommended_hours="4小时",
            area="浦东新区",
            ticket_price=130,
        ),
        _poi(
            "上海",
            "上海科技馆",
            "attraction",
            description="科普互动展馆，适合家庭",
            tags=["科技", "亲子", "室内"],
            recommended_hours="3小时",
            area="浦东新区",
            indoor_outdoor="indoor",
            ticket_price=45,
        ),
        _poi(
            "上海",
            "上海海洋水族馆",
            "attraction",
            description="陆家嘴大型水族馆",
            tags=["海洋", "亲子", "室内"],
            recommended_hours="3小时",
            area="陆家嘴",
            indoor_outdoor="indoor",
            ticket_price=160,
        ),
        _poi(
            "上海",
            "中华艺术宫",
            "attraction",
            description="原世博中国馆，艺术展览",
            tags=["艺术", "文化", "室内"],
            recommended_hours="2小时",
            area="世博",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "世博文化公园",
            "attraction",
            description="世博滨江绿地与景观",
            tags=["公园", "滨江", "户外"],
            recommended_hours="2小时",
            area="世博",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "静安寺",
            "attraction",
            description="上海著名佛教寺院",
            tags=["寺庙", "历史", "文化"],
            recommended_hours="1小时",
            area="静安区",
            ticket_price=50,
        ),
        _poi(
            "上海",
            "上海大剧院",
            "attraction",
            description="人民广场地标性艺术场馆",
            tags=["演出", "艺术", "室内"],
            recommended_hours="1-2小时",
            area="人民广场",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "思南公馆",
            "attraction",
            description="花园洋房历史文化街区",
            tags=["历史", "文艺", "建筑"],
            recommended_hours="2小时",
            area="黄浦区",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "武康路",
            "attraction",
            description="上海历史风貌街道",
            tags=["历史", "拍照", "街道"],
            recommended_hours="2小时",
            area="徐汇区",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "上海中心大厦",
            "attraction",
            description="中国第一高楼观景台",
            tags=["地标", "观景", "现代"],
            recommended_hours="2-3小时",
            area="陆家嘴",
            indoor_outdoor="mixed",
            ticket_price=180,
        ),
        _poi(
            "上海",
            "环球金融中心",
            "attraction",
            description="陆家嘴高层观光",
            tags=["地标", "观景", "现代"],
            recommended_hours="2小时",
            area="陆家嘴",
            indoor_outdoor="indoor",
            ticket_price=150,
        ),
        _poi(
            "上海",
            "龙华寺",
            "attraction",
            description="千年古刹，上海历史名寺",
            tags=["寺庙", "历史", "文化"],
            recommended_hours="2小时",
            area="徐汇区",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "共青国家森林公园",
            "attraction",
            description="城市森林湿地公园",
            tags=["自然", "森林", "户外"],
            recommended_hours="3小时",
            area="杨浦区",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "辰山植物园",
            "attraction",
            description="大型综合植物园",
            tags=["植物", "自然", "户外"],
            recommended_hours="3小时",
            area="松江区",
            ticket_price=60,
        ),
        _poi(
            "上海",
            "1933老场坊",
            "attraction",
            description="创意园区与历史建筑",
            tags=["创意", "建筑", "拍照"],
            recommended_hours="2小时",
            area="虹口区",
            ticket_price=0,
        ),
        _poi(
            "上海",
            "小杨生煎",
            "restaurant",
            description="上海经典生煎",
            tags=["生煎", "小吃", "老字号"],
        ),
        _poi(
            "上海",
            "南翔馒头店",
            "restaurant",
            description="著名小笼包",
            tags=["小笼包", "老字号", "小吃"],
        ),
        _poi(
            "上海",
            "老正兴菜馆",
            "restaurant",
            description="本帮菜老字号",
            tags=["本帮菜", "老字号", "中餐"],
        ),
        _poi(
            "上海",
            "德兴馆",
            "restaurant",
            description="上海传统面馆",
            tags=["面食", "老字号", "小吃"],
        ),
        _poi(
            "上海",
            "鲜得来排骨年糕",
            "restaurant",
            description="上海特色排骨年糕",
            tags=["小吃", "年糕", "特色"],
        ),
    ],
    "北京": [
        _poi(
            "北京",
            "圆明园",
            "attraction",
            description="清代皇家园林遗址",
            tags=["历史", "园林", "户外"],
            recommended_hours="3小时",
            area="海淀区",
            ticket_price=25,
        ),
        _poi(
            "北京",
            "香山公园",
            "attraction",
            description="皇家园林与自然景观",
            tags=["自然", "登山", "户外"],
            recommended_hours="4小时",
            area="海淀区",
            ticket_price=10,
        ),
        _poi(
            "北京",
            "北京动物园",
            "attraction",
            description="国内著名动物园",
            tags=["亲子", "动物", "户外"],
            recommended_hours="3小时",
            area="西城区",
            ticket_price=15,
        ),
        _poi(
            "北京",
            "国家大剧院",
            "attraction",
            description="标志性表演艺术中心",
            tags=["艺术", "建筑", "室内"],
            recommended_hours="2小时",
            area="西城区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "首都博物馆",
            "attraction",
            description="北京历史文物综合博物馆",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="西城区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "孔庙和国子监",
            "attraction",
            description="元明清最高学府遗址",
            tags=["历史", "文化", "古建筑"],
            recommended_hours="2小时",
            area="东城区",
            ticket_price=30,
        ),
        _poi(
            "北京",
            "什刹海",
            "attraction",
            description="老北京水乡风貌",
            tags=["湖泊", "胡同", "夜景"],
            recommended_hours="2小时",
            area="西城区",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "明十三陵",
            "attraction",
            description="明朝帝王陵寝群",
            tags=["历史", "陵墓", "户外"],
            recommended_hours="4小时",
            area="昌平区",
            ticket_price=60,
        ),
        _poi(
            "北京",
            "北京植物园",
            "attraction",
            description="大型植物园与温室",
            tags=["植物", "自然", "户外"],
            recommended_hours="3小时",
            area="海淀区",
            ticket_price=10,
        ),
        _poi(
            "北京",
            "奥林匹克森林公园",
            "attraction",
            description="城市森林公园",
            tags=["公园", "自然", "户外"],
            recommended_hours="3小时",
            area="朝阳区",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "潭柘寺",
            "attraction",
            description="北京最古老寺庙",
            tags=["寺庙", "历史", "文化"],
            recommended_hours="3小时",
            area="门头沟区",
            ticket_price=50,
        ),
        _poi(
            "北京",
            "古北水镇",
            "attraction",
            description="北方水乡度假小镇",
            tags=["古镇", "夜景", "度假"],
            recommended_hours="半天",
            area="密云区",
            ticket_price=140,
        ),
        _poi(
            "北京",
            "三里屯太古里",
            "attraction",
            description="时尚购物与潮流街区",
            tags=["购物", "时尚", "夜生活"],
            recommended_hours="2小时",
            area="朝阳区",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "前门大街",
            "attraction",
            description="老北京商业步行街",
            tags=["历史", "购物", "美食"],
            recommended_hours="2小时",
            area="东城区",
            ticket_price=0,
        ),
        _poi(
            "北京",
            "北京大观园",
            "attraction",
            description="红楼梦主题园林",
            tags=["园林", "文化", "拍照"],
            recommended_hours="2小时",
            area="西城区",
            ticket_price=40,
        ),
        _poi(
            "北京",
            "全聚德",
            "restaurant",
            description="著名北京烤鸭",
            tags=["烤鸭", "老字号", "中餐"],
        ),
        _poi(
            "北京",
            "便宜坊",
            "restaurant",
            description="焖炉烤鸭老字号",
            tags=["烤鸭", "老字号", "中餐"],
        ),
        _poi(
            "北京",
            "护国寺小吃",
            "restaurant",
            description="北京传统小吃集合",
            tags=["小吃", "老北京", "特色"],
        ),
        _poi(
            "北京",
            "姚记炒肝",
            "restaurant",
            description="老北京炒肝知名店",
            tags=["炒肝", "老北京", "小吃"],
        ),
        _poi(
            "北京",
            "海碗居",
            "restaurant",
            description="北京炸酱面",
            tags=["炸酱面", "老北京", "面食"],
        ),
    ],
    "广州": [
        _poi(
            "广州",
            "越秀公园",
            "attraction",
            description="城市中心公园，五羊雕像",
            tags=["公园", "地标", "户外"],
            recommended_hours="3小时",
            area="越秀区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "中山纪念堂",
            "attraction",
            description="孙中山纪念建筑",
            tags=["历史", "建筑", "文化"],
            recommended_hours="1小时",
            area="越秀区",
            ticket_price=10,
        ),
        _poi(
            "广州",
            "荔枝湾涌",
            "attraction",
            description="西关水乡风情",
            tags=["水乡", "历史", "西关"],
            recommended_hours="2小时",
            area="荔湾区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "西关大屋",
            "attraction",
            description="岭南传统民居",
            tags=["历史", "建筑", "西关"],
            recommended_hours="1小时",
            area="荔湾区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "广州大剧院",
            "attraction",
            description="珠江新城艺术地标",
            tags=["艺术", "建筑", "现代"],
            recommended_hours="1-2小时",
            area="天河区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "华南植物园",
            "attraction",
            description="大型热带植物园",
            tags=["植物", "自然", "户外"],
            recommended_hours="3小时",
            area="天河区",
            ticket_price=20,
        ),
        _poi(
            "广州",
            "黄埔军校旧址",
            "attraction",
            description="近代军事学校遗址",
            tags=["历史", "军事", "文化"],
            recommended_hours="2小时",
            area="黄埔区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "南沙天后宫",
            "attraction",
            description="沿海妈祖文化建筑",
            tags=["寺庙", "海景", "户外"],
            recommended_hours="2小时",
            area="南沙区",
            ticket_price=20,
        ),
        _poi(
            "广州",
            "长隆野生动物世界",
            "attraction",
            description="大型野生动物主题乐园",
            tags=["亲子", "动物", "户外"],
            recommended_hours="半天",
            area="番禺区",
            ticket_price=300,
        ),
        _poi(
            "广州",
            "长隆欢乐世界",
            "attraction",
            description="大型游乐园",
            tags=["亲子", "游乐", "户外"],
            recommended_hours="半天",
            area="番禺区",
            ticket_price=250,
        ),
        _poi(
            "广州",
            "石室圣心大教堂",
            "attraction",
            description="哥特式天主教堂",
            tags=["建筑", "宗教", "历史"],
            recommended_hours="1小时",
            area="越秀区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "广州博物馆",
            "attraction",
            description="广州历史文物展",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="越秀区",
            indoor_outdoor="indoor",
            ticket_price=10,
        ),
        _poi(
            "广州",
            "珠江新城",
            "attraction",
            description="广州CBD与花城广场",
            tags=["地标", "现代", "夜景"],
            recommended_hours="2小时",
            area="天河区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "太古仓码头",
            "attraction",
            description="滨江创意餐饮码头",
            tags=["夜景", "餐饮", "滨江"],
            recommended_hours="2小时",
            area="海珠区",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "南越王博物院",
            "attraction",
            description="南越国历史遗址",
            tags=["博物馆", "历史", "考古"],
            recommended_hours="2小时",
            area="越秀区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "广州",
            "陶陶居",
            "restaurant",
            description="广式早茶老字号",
            tags=["早茶", "粤菜", "老字号"],
        ),
        _poi(
            "广州",
            "广州酒家",
            "restaurant",
            description="粤菜老字号",
            tags=["粤菜", "早茶", "老字号"],
        ),
        _poi(
            "广州",
            "莲香楼",
            "restaurant",
            description="传统粤式茶楼",
            tags=["早茶", "糕点", "老字号"],
        ),
        _poi(
            "广州",
            "点都德",
            "restaurant",
            description="新式粤式茶点",
            tags=["早茶", "点心", "连锁"],
        ),
        _poi(
            "广州", "炳胜品味", "restaurant", description="精品粤菜", tags=["粤菜", "正餐", "高端"]
        ),
    ],
    "成都": [
        _poi(
            "成都",
            "人民公园",
            "attraction",
            description="成都休闲茶文化公园",
            tags=["公园", "茶文化", "休闲"],
            recommended_hours="2小时",
            area="青羊区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "天府广场",
            "attraction",
            description="成都市中心地标广场",
            tags=["地标", "城市", "广场"],
            recommended_hours="1小时",
            area="青羊区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "成都博物馆",
            "attraction",
            description="成都通史与民俗展",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="青羊区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "四川科技馆",
            "attraction",
            description="科普互动展馆",
            tags=["科技", "亲子", "室内"],
            recommended_hours="2小时",
            area="青羊区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "东郊记忆",
            "attraction",
            description="工业遗址音乐公园",
            tags=["文艺", "音乐", "拍照"],
            recommended_hours="2小时",
            area="成华区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "昭觉寺",
            "attraction",
            description="川西第一禅林",
            tags=["寺庙", "历史", "文化"],
            recommended_hours="2小时",
            area="成华区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "永陵博物馆",
            "attraction",
            description="前蜀王王建陵墓",
            tags=["博物馆", "历史", "陵墓"],
            recommended_hours="2小时",
            area="金牛区",
            ticket_price=20,
        ),
        _poi(
            "成都",
            "浣花溪公园",
            "attraction",
            description="诗歌文化主题公园",
            tags=["公园", "诗歌", "自然"],
            recommended_hours="2小时",
            area="青羊区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "黄龙溪古镇",
            "attraction",
            description="川西水乡古镇",
            tags=["古镇", "水乡", "休闲"],
            recommended_hours="3小时",
            area="双流区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "洛带古镇",
            "attraction",
            description="客家文化古镇",
            tags=["古镇", "客家", "文化"],
            recommended_hours="3小时",
            area="龙泉驿区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "西岭雪山",
            "attraction",
            description="成都近郊雪山景区",
            tags=["雪山", "自然", "户外"],
            recommended_hours="半天",
            area="大邑县",
            ticket_price=120,
        ),
        _poi(
            "成都",
            "成都欢乐谷",
            "attraction",
            description="大型主题游乐园",
            tags=["亲子", "游乐", "户外"],
            recommended_hours="半天",
            area="金牛区",
            ticket_price=230,
        ),
        _poi(
            "成都",
            "望江楼公园",
            "attraction",
            description="竹文化与薛涛纪念公园",
            tags=["公园", "竹子", "文化"],
            recommended_hours="2小时",
            area="武侯区",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "青羊宫",
            "attraction",
            description="川西第一道观",
            tags=["道教", "历史", "文化"],
            recommended_hours="2小时",
            area="青羊区",
            ticket_price=10,
        ),
        _poi(
            "成都",
            "四川博物院",
            "attraction",
            description="四川历史艺术综合博物馆",
            tags=["博物馆", "历史", "艺术"],
            recommended_hours="2小时",
            area="青羊区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "成都",
            "陈麻婆豆腐",
            "restaurant",
            description="正宗麻婆豆腐",
            tags=["川菜", "老字号", "豆腐"],
        ),
        _poi(
            "成都",
            "夫妻肺片",
            "restaurant",
            description="成都经典凉菜",
            tags=["川菜", "小吃", "老字号"],
        ),
        _poi(
            "成都",
            "龙抄手",
            "restaurant",
            description="成都名小吃抄手",
            tags=["小吃", "面食", "老字号"],
        ),
        _poi(
            "成都",
            "钟水饺",
            "restaurant",
            description="成都传统水饺",
            tags=["小吃", "面食", "老字号"],
        ),
        _poi(
            "成都",
            "担担面",
            "restaurant",
            description="四川特色面食",
            tags=["面食", "川菜", "小吃"],
        ),
    ],
    "杭州": [
        _poi(
            "杭州",
            "宋城",
            "attraction",
            description="宋代文化主题乐园",
            tags=["文化", "演出", "亲子"],
            recommended_hours="半天",
            area="西湖区",
            ticket_price=300,
        ),
        _poi(
            "杭州",
            "河坊街",
            "attraction",
            description="杭州传统商业街",
            tags=["购物", "美食", "历史"],
            recommended_hours="2小时",
            area="上城区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "南宋御街",
            "attraction",
            description="南宋皇城遗址商业街",
            tags=["历史", "街道", "文化"],
            recommended_hours="2小时",
            area="上城区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "杭州博物馆",
            "attraction",
            description="杭州历史文物展",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="上城区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "中国丝绸博物馆",
            "attraction",
            description="丝绸文化专题博物馆",
            tags=["博物馆", "丝绸", "文化"],
            recommended_hours="2小时",
            area="西湖区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "浙江省博物馆",
            "attraction",
            description="浙江省综合博物馆",
            tags=["博物馆", "历史", "艺术"],
            recommended_hours="2小时",
            area="西湖区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "杭州植物园",
            "attraction",
            description="西湖边大型植物园",
            tags=["植物", "自然", "户外"],
            recommended_hours="3小时",
            area="西湖区",
            ticket_price=10,
        ),
        _poi(
            "杭州",
            "云栖竹径",
            "attraction",
            description="竹林古道徒步",
            tags=["自然", "竹林", "徒步"],
            recommended_hours="2小时",
            area="西湖区",
            ticket_price=8,
        ),
        _poi(
            "杭州",
            "九溪烟树",
            "attraction",
            description="西湖九溪徒步赏景",
            tags=["自然", "溪流", "徒步"],
            recommended_hours="3小时",
            area="西湖区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "虎跑梦泉",
            "attraction",
            description="泉水与济公传说",
            tags=["自然", "泉水", "文化"],
            recommended_hours="2小时",
            area="西湖区",
            ticket_price=15,
        ),
        _poi(
            "杭州",
            "六和塔",
            "attraction",
            description="钱塘江畔古塔",
            tags=["古塔", "历史", "观景"],
            recommended_hours="1小时",
            area="西湖区",
            ticket_price=20,
        ),
        _poi(
            "杭州",
            "京杭大运河",
            "attraction",
            description="古运河杭州段",
            tags=["运河", "历史", "水上"],
            recommended_hours="2小时",
            area="拱墅区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "拱宸桥",
            "attraction",
            description="京杭大运河标志性古桥",
            tags=["古桥", "历史", "运河"],
            recommended_hours="1小时",
            area="拱墅区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "良渚古城遗址",
            "attraction",
            description="世界文化遗产史前遗址",
            tags=["遗址", "历史", "文化"],
            recommended_hours="3小时",
            area="余杭区",
            ticket_price=60,
        ),
        _poi(
            "杭州",
            "湘湖",
            "attraction",
            description="萧山休闲湖泊",
            tags=["湖泊", "自然", "户外"],
            recommended_hours="3小时",
            area="萧山区",
            ticket_price=0,
        ),
        _poi(
            "杭州",
            "楼外楼",
            "restaurant",
            description="西湖醋鱼名店",
            tags=["杭帮菜", "老字号", "鱼"],
        ),
        _poi(
            "杭州",
            "知味观",
            "restaurant",
            description="杭州传统小吃",
            tags=["小吃", "杭帮菜", "老字号"],
        ),
        _poi(
            "杭州",
            "外婆家",
            "restaurant",
            description="大众杭帮菜连锁",
            tags=["杭帮菜", "家常菜", "连锁"],
        ),
        _poi(
            "杭州",
            "绿茶餐厅",
            "restaurant",
            description="创意杭帮菜",
            tags=["杭帮菜", "创意菜", "连锁"],
        ),
        _poi(
            "杭州",
            "新白鹿",
            "restaurant",
            description="杭州家常菜连锁",
            tags=["杭帮菜", "家常菜", "连锁"],
        ),
    ],
    "西安": [
        _poi(
            "西安",
            "大明宫国家遗址公园",
            "attraction",
            description="唐代大明宫遗址",
            tags=["遗址", "历史", "唐代"],
            recommended_hours="3小时",
            area="新城区",
            ticket_price=60,
        ),
        _poi(
            "西安",
            "大唐不夜城",
            "attraction",
            description="唐风文化步行街",
            tags=["夜景", "文化", "步行街"],
            recommended_hours="2小时",
            area="雁塔区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "骊山",
            "attraction",
            description="华清宫旁山景与历史",
            tags=["山景", "历史", "户外"],
            recommended_hours="3小时",
            area="临潼区",
            ticket_price=120,
        ),
        _poi(
            "西安",
            "西安博物院",
            "attraction",
            description="西安历史文物与小雁塔",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="碑林区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "碑林博物馆",
            "attraction",
            description="历代碑刻书法宝库",
            tags=["博物馆", "书法", "历史"],
            recommended_hours="2小时",
            area="碑林区",
            indoor_outdoor="indoor",
            ticket_price=65,
        ),
        _poi(
            "西安",
            "永兴坊",
            "attraction",
            description="陕西非遗美食街区",
            tags=["美食", "非遗", "文化"],
            recommended_hours="2小时",
            area="新城区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "半坡博物馆",
            "attraction",
            description="新石器时代遗址",
            tags=["博物馆", "遗址", "历史"],
            recommended_hours="2小时",
            area="灞桥区",
            indoor_outdoor="indoor",
            ticket_price=55,
        ),
        _poi(
            "西安",
            "青龙寺",
            "attraction",
            description="唐代密宗寺院与樱花",
            tags=["寺庙", "历史", "樱花"],
            recommended_hours="2小时",
            area="雁塔区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "兴庆宫公园",
            "attraction",
            description="唐代兴庆宫遗址公园",
            tags=["公园", "历史", "休闲"],
            recommended_hours="2小时",
            area="碑林区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "曲江池遗址公园",
            "attraction",
            description="唐代曲江池遗址",
            tags=["公园", "历史", "湖泊"],
            recommended_hours="2小时",
            area="雁塔区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "汉城湖",
            "attraction",
            description="汉代长安城护城河遗址",
            tags=["湖泊", "历史", "户外"],
            recommended_hours="2小时",
            area="未央区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "秦岭野生动物园",
            "attraction",
            description="西安近郊野生动物园",
            tags=["亲子", "动物", "户外"],
            recommended_hours="4小时",
            area="长安区",
            ticket_price=100,
        ),
        _poi(
            "西安",
            "陕西自然博物馆",
            "attraction",
            description="自然科普博物馆",
            tags=["博物馆", "亲子", "自然"],
            recommended_hours="2小时",
            area="雁塔区",
            indoor_outdoor="indoor",
            ticket_price=30,
        ),
        _poi(
            "西安",
            "西安世博园",
            "attraction",
            description="世园会遗址公园",
            tags=["公园", "世博", "户外"],
            recommended_hours="2小时",
            area="灞桥区",
            ticket_price=0,
        ),
        _poi(
            "西安",
            "长安十二时辰主题街区",
            "attraction",
            description="唐风沉浸式主题街区",
            tags=["文化", "唐风", "沉浸式"],
            recommended_hours="2小时",
            area="雁塔区",
            ticket_price=68,
        ),
        _poi(
            "西安",
            "肉夹馍",
            "restaurant",
            description="西安经典小吃",
            tags=["小吃", "面食", "特色"],
        ),
        _poi(
            "西安", "凉皮", "restaurant", description="陕西风味凉皮", tags=["小吃", "面食", "特色"]
        ),
        _poi(
            "西安",
            "羊肉泡馍",
            "restaurant",
            description="西安传统主食",
            tags=["主食", "面食", "老字号"],
        ),
        _poi(
            "西安",
            "岐山臊子面",
            "restaurant",
            description="陕西特色面条",
            tags=["面食", "陕西", "小吃"],
        ),
        _poi(
            "西安",
            "贾三灌汤包",
            "restaurant",
            description="西安灌汤包名店",
            tags=["小吃", "包子", "老字号"],
        ),
    ],
    "重庆": [
        _poi(
            "重庆",
            "李子坝轻轨站",
            "attraction",
            description="轻轨穿楼奇观",
            tags=["网红", "交通", "拍照"],
            recommended_hours="1小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "鹅岭二厂",
            "attraction",
            description="老厂房改造文创园",
            tags=["文创", "拍照", "文艺"],
            recommended_hours="2小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "南山一棵树",
            "attraction",
            description="重庆夜景观景台",
            tags=["夜景", "观景", "户外"],
            recommended_hours="2小时",
            area="南岸区",
            ticket_price=30,
        ),
        _poi(
            "重庆",
            "重庆中国三峡博物馆",
            "attraction",
            description="三峡与巴渝文化",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="渝中区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "人民大礼堂",
            "attraction",
            description="重庆地标建筑群",
            tags=["地标", "建筑", "文化"],
            recommended_hours="1小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "武隆天生三桥",
            "attraction",
            description="喀斯特地貌自然奇观",
            tags=["自然", "世界自然遗产", "户外"],
            recommended_hours="半天",
            area="武隆区",
            ticket_price=125,
        ),
        _poi(
            "重庆",
            "大足石刻",
            "attraction",
            description="世界文化遗产石窟艺术",
            tags=["石窟", "历史", "文化"],
            recommended_hours="半天",
            area="大足区",
            ticket_price=140,
        ),
        _poi(
            "重庆",
            "金佛山",
            "attraction",
            description="南方喀斯特山岳景区",
            tags=["山岳", "自然", "户外"],
            recommended_hours="半天",
            area="南川区",
            ticket_price=80,
        ),
        _poi(
            "重庆",
            "朝天门广场",
            "attraction",
            description="两江交汇广场",
            tags=["地标", "江景", "广场"],
            recommended_hours="1小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "山城步道",
            "attraction",
            description="悬空临江老城步道",
            tags=["徒步", "历史", "江景"],
            recommended_hours="2小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "下浩老街",
            "attraction",
            description="南岸复古文创街区",
            tags=["老街", "文创", "拍照"],
            recommended_hours="2小时",
            area="南岸区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "白象居",
            "attraction",
            description="老重庆民居与空中连廊",
            tags=["网红", "建筑", "拍照"],
            recommended_hours="1小时",
            area="渝中区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "湖广会馆",
            "attraction",
            description="清代移民会馆建筑群",
            tags=["历史", "建筑", "文化"],
            recommended_hours="2小时",
            area="渝中区",
            ticket_price=25,
        ),
        _poi(
            "重庆",
            "长江索道",
            "attraction",
            description="跨江空中交通体验",
            tags=["交通", "江景", "体验"],
            recommended_hours="1小时",
            area="渝中区",
            ticket_price=20,
        ),
        _poi(
            "重庆",
            "渣滓洞",
            "attraction",
            description="红岩革命历史遗址",
            tags=["历史", "红色", "纪念"],
            recommended_hours="2小时",
            area="沙坪坝区",
            ticket_price=0,
        ),
        _poi(
            "重庆",
            "重庆小面",
            "restaurant",
            description="重庆特色面食",
            tags=["面食", "辣", "小吃"],
        ),
        _poi("重庆", "酸辣粉", "restaurant", description="重庆酸辣粉", tags=["小吃", "辣", "粉"]),
        _poi(
            "重庆", "串串香", "restaurant", description="重庆串串火锅", tags=["火锅", "辣", "小吃"]
        ),
        _poi(
            "重庆",
            "豆花饭",
            "restaurant",
            description="重庆传统豆花",
            tags=["豆花", "米饭", "小吃"],
        ),
        _poi("重庆", "毛血旺", "restaurant", description="重庆江湖菜", tags=["川菜", "辣", "正餐"]),
    ],
    "深圳": [
        _poi(
            "深圳",
            "深圳湾公园",
            "attraction",
            description="滨海城市公园",
            tags=["海滨", "公园", "户外"],
            recommended_hours="3小时",
            area="南山区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "莲花山公园",
            "attraction",
            description="市中心山地公园",
            tags=["公园", "登山", "户外"],
            recommended_hours="2小时",
            area="福田区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "世界之窗",
            "attraction",
            description="世界名胜微缩景区",
            tags=["主题公园", "亲子", "户外"],
            recommended_hours="4小时",
            area="南山区",
            ticket_price=220,
        ),
        _poi(
            "深圳",
            "欢乐谷",
            "attraction",
            description="大型主题游乐园",
            tags=["亲子", "游乐", "户外"],
            recommended_hours="4小时",
            area="南山区",
            ticket_price=230,
        ),
        _poi(
            "深圳",
            "东部华侨城",
            "attraction",
            description="山海度假旅游区",
            tags=["度假", "自然", "亲子"],
            recommended_hours="半天",
            area="盐田区",
            ticket_price=200,
        ),
        _poi(
            "深圳",
            "大梅沙海滨公园",
            "attraction",
            description="城市海滨浴场",
            tags=["海滩", "户外", "亲子"],
            recommended_hours="3小时",
            area="盐田区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "小梅沙",
            "attraction",
            description="滨海旅游度假区",
            tags=["海滩", "度假", "户外"],
            recommended_hours="3小时",
            area="盐田区",
            ticket_price=50,
        ),
        _poi(
            "深圳",
            "大鹏所城",
            "attraction",
            description="明清海防古城",
            tags=["古城", "历史", "户外"],
            recommended_hours="3小时",
            area="大鹏新区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "较场尾",
            "attraction",
            description="海滨民宿小镇",
            tags=["海滩", "民宿", "休闲"],
            recommended_hours="2小时",
            area="大鹏新区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "锦绣中华",
            "attraction",
            description="中国名胜微缩景区",
            tags=["主题公园", "文化", "户外"],
            recommended_hours="4小时",
            area="南山区",
            ticket_price=220,
        ),
        _poi(
            "深圳",
            "华强北",
            "attraction",
            description="电子商业与购物街区",
            tags=["购物", "电子", "城市"],
            recommended_hours="2小时",
            area="福田区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "深圳博物馆",
            "attraction",
            description="深圳历史与民俗展",
            tags=["博物馆", "历史", "文化"],
            recommended_hours="2小时",
            area="福田区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "海上世界",
            "attraction",
            description="滨海休闲与艺术区",
            tags=["海滨", "艺术", "餐饮"],
            recommended_hours="2小时",
            area="南山区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "仙湖植物园",
            "attraction",
            description="弘法寺与植物园",
            tags=["植物", "寺庙", "户外"],
            recommended_hours="3小时",
            area="罗湖区",
            ticket_price=15,
        ),
        _poi(
            "深圳",
            "梧桐山",
            "attraction",
            description="深圳最高峰登山",
            tags=["登山", "自然", "户外"],
            recommended_hours="4小时",
            area="罗湖区",
            ticket_price=0,
        ),
        _poi(
            "深圳",
            "潮汕牛肉火锅",
            "restaurant",
            description="鲜切牛肉火锅",
            tags=["火锅", "牛肉", "广东"],
        ),
        _poi(
            "深圳",
            "港式茶餐厅",
            "restaurant",
            description="港式快餐与茶点",
            tags=["港式", "茶餐厅", "快餐"],
        ),
        _poi(
            "深圳",
            "椰子鸡",
            "restaurant",
            description="深圳流行火锅",
            tags=["火锅", "椰子", "鸡肉"],
        ),
        _poi(
            "深圳",
            "海鲜大排档",
            "restaurant",
            description="沿海城市海鲜",
            tags=["海鲜", "大排档", "广东"],
        ),
        _poi(
            "深圳", "肠粉", "restaurant", description="广式早餐肠粉", tags=["早餐", "肠粉", "小吃"]
        ),
    ],
    "南京": [
        _poi(
            "南京",
            "南京博物院",
            "attraction",
            description="中国三大博物馆之一",
            tags=["博物馆", "历史", "艺术"],
            recommended_hours="2小时",
            area="玄武区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "侵华日军南京大屠杀遇难同胞纪念馆",
            "attraction",
            description="历史纪念场馆",
            tags=["纪念馆", "历史", "和平"],
            recommended_hours="2小时",
            area="建邺区",
            indoor_outdoor="indoor",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "玄武湖公园",
            "attraction",
            description="江南三大名湖之一",
            tags=["湖泊", "公园", "户外"],
            recommended_hours="3小时",
            area="玄武区",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "鸡鸣寺",
            "attraction",
            description="南京千年古刹",
            tags=["寺庙", "历史", "樱花"],
            recommended_hours="1小时",
            area="玄武区",
            ticket_price=10,
        ),
        _poi(
            "南京",
            "朝天宫",
            "attraction",
            description="江南最大明清官式古建筑群",
            tags=["古建筑", "历史", "博物馆"],
            recommended_hours="2小时",
            area="秦淮区",
            ticket_price=25,
        ),
        _poi(
            "南京",
            "阅江楼",
            "attraction",
            description="江南四大名楼之一",
            tags=["古楼", "江景", "历史"],
            recommended_hours="2小时",
            area="鼓楼区",
            ticket_price=40,
        ),
        _poi(
            "南京",
            "栖霞山",
            "attraction",
            description="金陵第一明秀山",
            tags=["山岳", "自然", "红叶"],
            recommended_hours="4小时",
            area="栖霞区",
            ticket_price=40,
        ),
        _poi(
            "南京",
            "老门东",
            "attraction",
            description="南京传统民居街区",
            tags=["历史", "街道", "美食"],
            recommended_hours="2小时",
            area="秦淮区",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "中华门城堡",
            "attraction",
            description="明代城墙城门",
            tags=["城墙", "历史", "古建筑"],
            recommended_hours="1小时",
            area="秦淮区",
            ticket_price=50,
        ),
        _poi(
            "南京",
            "南京长江大桥",
            "attraction",
            description="长江上第一座由中国设计建造的双层桥",
            tags=["桥梁", "地标", "江景"],
            recommended_hours="1小时",
            area="鼓楼区",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "牛首山文化旅游区",
            "attraction",
            description="佛教文化与自然景观",
            tags=["佛教", "文化", "户外"],
            recommended_hours="3小时",
            area="江宁区",
            ticket_price=98,
        ),
        _poi(
            "南京",
            "大报恩寺遗址",
            "attraction",
            description="明代大报恩寺遗址公园",
            tags=["遗址", "历史", "佛教"],
            recommended_hours="2小时",
            area="秦淮区",
            ticket_price=90,
        ),
        _poi(
            "南京",
            "明孝陵",
            "attraction",
            description="明太祖朱元璋陵墓",
            tags=["陵墓", "历史", "户外"],
            recommended_hours="3小时",
            area="玄武区",
            ticket_price=70,
        ),
        _poi(
            "南京",
            "中山陵",
            "attraction",
            description="孙中山先生陵寝",
            tags=["纪念", "历史", "户外"],
            recommended_hours="2小时",
            area="玄武区",
            ticket_price=0,
        ),
        _poi(
            "南京",
            "总统府",
            "attraction",
            description="近代历史建筑群",
            tags=["历史", "建筑", "近代"],
            recommended_hours="2小时",
            area="玄武区",
            ticket_price=35,
        ),
        _poi(
            "南京",
            "鸭血粉丝汤",
            "restaurant",
            description="南京经典小吃",
            tags=["小吃", "汤", "特色"],
        ),
        _poi(
            "南京", "盐水鸭", "restaurant", description="南京名菜", tags=["鸭肉", "老字号", "特色"]
        ),
        _poi(
            "南京", "小笼包", "restaurant", description="江南小笼包", tags=["包子", "小吃", "江南"]
        ),
        _poi(
            "南京",
            "皮肚面",
            "restaurant",
            description="南京特色面食",
            tags=["面食", "小吃", "特色"],
        ),
        _poi(
            "南京",
            "糖芋苗",
            "restaurant",
            description="南京传统甜品",
            tags=["甜品", "小吃", "传统"],
        ),
    ],
    "厦门": [
        _poi(
            "厦门",
            "集美学村",
            "attraction",
            description="嘉庚风格教育与建筑群",
            tags=["教育", "建筑", "文化"],
            recommended_hours="2小时",
            area="集美区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "园博苑",
            "attraction",
            description="大型园林博览园",
            tags=["园林", "公园", "户外"],
            recommended_hours="3小时",
            area="集美区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "厦门植物园",
            "attraction",
            description="热带雨林与多肉植物",
            tags=["植物", "自然", "户外"],
            recommended_hours="3小时",
            area="思明区",
            ticket_price=30,
        ),
        _poi(
            "厦门",
            "中山路步行街",
            "attraction",
            description="厦门传统商业街",
            tags=["购物", "美食", "街道"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "沙坡尾",
            "attraction",
            description="文艺渔港街区",
            tags=["文艺", "渔港", "拍照"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "胡里山炮台",
            "attraction",
            description="海防历史炮台",
            tags=["历史", "海防", "海景"],
            recommended_hours="1小时",
            area="思明区",
            ticket_price=25,
        ),
        _poi(
            "厦门",
            "白城沙滩",
            "attraction",
            description="环岛路海滨沙滩",
            tags=["海滩", "户外", "休闲"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "五缘湾湿地公园",
            "attraction",
            description="城市湿地公园",
            tags=["湿地", "自然", "户外"],
            recommended_hours="2小时",
            area="湖里区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "观音山",
            "attraction",
            description="海滨游乐商务区",
            tags=["海滨", "游乐", "户外"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "方特梦幻王国",
            "attraction",
            description="大型主题乐园",
            tags=["亲子", "游乐", "户外"],
            recommended_hours="半天",
            area="同安区",
            ticket_price=230,
        ),
        _poi(
            "厦门",
            "鼓浪屿",
            "attraction",
            description="世界文化遗产海岛",
            tags=["海岛", "历史", "建筑"],
            recommended_hours="半天",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "南普陀寺",
            "attraction",
            description="厦门著名佛教寺院",
            tags=["寺庙", "历史", "文化"],
            recommended_hours="1小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "厦门大学",
            "attraction",
            description="中国最美大学之一",
            tags=["校园", "建筑", "文化"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "环岛路",
            "attraction",
            description="滨海观光公路",
            tags=["海滨", "骑行", "户外"],
            recommended_hours="3小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "曾厝垵",
            "attraction",
            description="文艺渔村小吃街",
            tags=["美食", "文艺", "街道"],
            recommended_hours="2小时",
            area="思明区",
            ticket_price=0,
        ),
        _poi(
            "厦门",
            "沙茶面",
            "restaurant",
            description="厦门特色面食",
            tags=["面食", "海鲜", "特色"],
        ),
        _poi(
            "厦门",
            "海蛎煎",
            "restaurant",
            description="厦门传统海鲜小吃",
            tags=["海鲜", "小吃", "特色"],
        ),
        _poi(
            "厦门",
            "土笋冻",
            "restaurant",
            description="闽南特色冻品",
            tags=["小吃", "闽南", "特色"],
        ),
        _poi(
            "厦门",
            "花生汤",
            "restaurant",
            description="厦门传统甜品",
            tags=["甜品", "小吃", "传统"],
        ),
        _poi("厦门", "烧肉粽", "restaurant", description="闽南肉粽", tags=["粽子", "闽南", "小吃"]),
    ],
    "青岛": [
        _poi(
            "青岛",
            "信号山公园",
            "attraction",
            description="老城制高点观红瓦绿树",
            tags=["观景", "公园", "户外"],
            recommended_hours="2小时",
            area="市南区",
            ticket_price=10,
        ),
        _poi(
            "青岛",
            "小鱼山公园",
            "attraction",
            description="俯瞰青岛湾与老城区的山丘公园",
            tags=["观景", "公园", "户外"],
            recommended_hours="2小时",
            area="市南区",
            ticket_price=10,
        ),
        _poi(
            "青岛",
            "第一海水浴场",
            "attraction",
            description="青岛老牌海滨浴场",
            tags=["海滩", "游泳", "户外"],
            recommended_hours="2小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "第二海水浴场",
            "attraction",
            description="汇泉湾海滨浴场",
            tags=["海滩", "休闲", "户外"],
            recommended_hours="2小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "奥帆中心",
            "attraction",
            description="奥运帆船比赛场地",
            tags=["奥运", "海滨", "帆船"],
            recommended_hours="2小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "极地海洋世界",
            "attraction",
            description="海洋动物表演与展馆",
            tags=["海洋", "亲子", "室内"],
            recommended_hours="3小时",
            area="崂山区",
            indoor_outdoor="indoor",
            ticket_price=220,
        ),
        _poi(
            "青岛",
            "金沙滩",
            "attraction",
            description="黄岛金色细沙滩",
            tags=["海滩", "户外", "休闲"],
            recommended_hours="3小时",
            area="黄岛区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "银沙滩",
            "attraction",
            description="西海岸银白色沙滩",
            tags=["海滩", "户外", "休闲"],
            recommended_hours="2小时",
            area="黄岛区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "德国总督楼旧址",
            "attraction",
            description="德式建筑博物馆",
            tags=["历史", "建筑", "德式"],
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="indoor",
            ticket_price=20,
        ),
        _poi(
            "青岛",
            "劈柴院",
            "attraction",
            description="青岛传统美食街",
            tags=["美食", "老街", "小吃"],
            recommended_hours="1小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "栈桥",
            "attraction",
            description="青岛海滨地标",
            tags=["海滨", "地标", "户外"],
            recommended_hours="1小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "八大关",
            "attraction",
            description="万国建筑博览别墅区",
            tags=["建筑", "历史", "拍照"],
            recommended_hours="3小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "崂山",
            "attraction",
            description="海上名山道教圣地",
            tags=["山岳", "道教", "自然"],
            recommended_hours="半天",
            area="崂山区",
            ticket_price=90,
        ),
        _poi(
            "青岛",
            "五四广场",
            "attraction",
            description="青岛城市地标广场",
            tags=["地标", "广场", "夜景"],
            recommended_hours="1小时",
            area="市南区",
            ticket_price=0,
        ),
        _poi(
            "青岛",
            "青岛啤酒博物馆",
            "attraction",
            description="青岛啤酒历史文化展馆",
            tags=["博物馆", "啤酒", "工业"],
            recommended_hours="2小时",
            area="市北区",
            indoor_outdoor="indoor",
            ticket_price=60,
        ),
        _poi(
            "青岛",
            "青岛啤酒",
            "restaurant",
            description="青岛本地啤酒",
            tags=["啤酒", "饮品", "本地"],
        ),
        _poi(
            "青岛",
            "海鲜水饺",
            "restaurant",
            description="青岛海鲜水饺",
            tags=["海鲜", "水饺", "主食"],
        ),
        _poi(
            "青岛",
            "辣炒蛤蜊",
            "restaurant",
            description="青岛经典海鲜",
            tags=["海鲜", "辣炒", "特色"],
        ),
        _poi(
            "青岛", "青岛烧烤", "restaurant", description="本地烧烤", tags=["烧烤", "夜宵", "本地"]
        ),
        _poi(
            "青岛",
            "排骨米饭",
            "restaurant",
            description="青岛特色快餐",
            tags=["米饭", "排骨", "快餐"],
        ),
    ],
}
