"""Built-in city POI data — deterministic fallback for 12 popular destinations.

Each POI includes location (lat/lng), ticket_price, tags, area, recommended_hours,
best_time, and indoor_outdoor for accurate route planning and budget calculation.

Originally extracted from ``agents/itinerary_planner.py`` to decouple data from
the old LangGraph planning agent.
"""

from schemas import ScoredPOI, Location

CITY_DEFAULTS: dict[str, list[ScoredPOI]] = {
    "上海": [
        ScoredPOI(
            name="外滩",
            category="attraction",
            score=0.9,
            description="万国建筑博览群，上海地标",
            tags=["夜景", "历史", "拍照"],
            best_time="晚上",
            recommended_hours="1-2小时",
            area="外滩",
            indoor_outdoor="outdoor",
            location=Location(lat=31.2397, lng=121.4998),
            ticket_price=0,
        ),
        ScoredPOI(
            name="东方明珠",
            category="attraction",
            score=0.9,
            description="上海标志性建筑，俯瞰全城",
            tags=["地标", "观景", "拍照"],
            best_time="全天",
            recommended_hours="2-3小时",
            area="陆家嘴",
            indoor_outdoor="mixed",
            location=Location(lat=31.2397, lng=121.4998),
            ticket_price=199,
        ),
        ScoredPOI(
            name="豫园",
            category="attraction",
            score=0.85,
            description="明代园林，江南古典园林代表",
            tags=["园林", "历史", "文化"],
            best_time="上午",
            recommended_hours="2小时",
            area="城隍庙",
            indoor_outdoor="mixed",
            location=Location(lat=31.2273, lng=121.4920),
            ticket_price=40,
        ),
        ScoredPOI(
            name="南京路步行街",
            category="attraction",
            score=0.8,
            description="中华商业第一街",
            tags=["购物", "美食", "逛街"],
            best_time="下午",
            recommended_hours="2小时",
            area="南京东路",
            indoor_outdoor="outdoor",
            location=Location(lat=31.2346, lng=121.4750),
            ticket_price=0,
        ),
        ScoredPOI(
            name="田子坊",
            category="attraction",
            score=0.8,
            description="石库门里弄，创意艺术区",
            tags=["文艺", "拍照", "小巷"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="打浦桥",
            indoor_outdoor="mixed",
            location=Location(lat=31.2106, lng=121.4692),
            ticket_price=0,
        ),
        ScoredPOI(
            name="新天地",
            category="attraction",
            score=0.8,
            description="石库门与现代融合的时尚地标",
            tags=["夜生活", "餐饮", "文化"],
            best_time="晚上",
            recommended_hours="2小时",
            area="新天地",
            indoor_outdoor="mixed",
            location=Location(lat=31.2225, lng=121.4753),
            ticket_price=0,
        ),
        ScoredPOI(
            name="陆家嘴",
            category="attraction",
            score=0.85,
            description="金融中心，摩天大楼群",
            tags=["地标", "现代", "观景"],
            best_time="全天",
            recommended_hours="2-3小时",
            area="陆家嘴",
            indoor_outdoor="mixed",
            location=Location(lat=31.2397, lng=121.4998),
            ticket_price=0,
        ),
        ScoredPOI(
            name="上海博物馆",
            category="attraction",
            score=0.8,
            description="中国古代艺术博物馆",
            tags=["博物馆", "历史", "文化"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="人民广场",
            indoor_outdoor="indoor",
            location=Location(lat=31.2283, lng=121.4453),
            ticket_price=0,
        ),
        ScoredPOI(
            name="城隍庙",
            category="attraction",
            score=0.75,
            description="道教庙宇，特色小吃街",
            tags=["美食", "文化", "传统"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="城隍庙",
            indoor_outdoor="mixed",
            location=Location(lat=31.2273, lng=121.4920),
            ticket_price=10,
        ),
        ScoredPOI(
            name="武康路",
            category="attraction",
            score=0.8,
            description="历史风貌街区，梧桐洋房",
            tags=["历史", "拍照", "文艺"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="徐汇区",
            indoor_outdoor="outdoor",
            location=Location(lat=31.2165, lng=121.4375),
            ticket_price=0,
        ),
        ScoredPOI(
            name="1933老场坊",
            category="attraction",
            score=0.7,
            description="创意园区，工业风建筑",
            tags=["建筑", "拍照", "艺术"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="虹口区",
            indoor_outdoor="mixed",
            location=Location(lat=31.2578, lng=121.4856),
            ticket_price=0,
        ),
        ScoredPOI(
            name="上海迪士尼",
            category="attraction",
            score=0.9,
            description="中国大陆首座迪士尼乐园",
            tags=["亲子", "娱乐", "主题公园"],
            best_time="全天",
            recommended_hours="全天",
            area="浦东新区",
            indoor_outdoor="mixed",
            location=Location(lat=31.1413, lng=121.6618),
            ticket_price=475,
        ),
        ScoredPOI(
            name="思南公馆",
            category="attraction",
            score=0.75,
            description="花园洋房建筑群",
            tags=["历史", "建筑", "休闲"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="复兴中路",
            indoor_outdoor="mixed",
            location=Location(lat=31.2183, lng=121.4692),
            ticket_price=0,
        ),
        ScoredPOI(
            name="M50创意园",
            category="attraction",
            score=0.7,
            description="艺术创意园区",
            tags=["艺术", "画廊", "文艺"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="莫干山路",
            indoor_outdoor="mixed",
            location=Location(lat=31.2469, lng=121.4453),
            ticket_price=0,
        ),
        ScoredPOI(
            name="七宝老街",
            category="attraction",
            score=0.7,
            description="古镇风貌美食街",
            tags=["美食", "古镇", "传统"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="闵行区",
            indoor_outdoor="outdoor",
            location=Location(lat=31.1575, lng=121.3531),
            ticket_price=0,
        ),
        ScoredPOI(
            name="南翔馒头店",
            category="restaurant",
            score=0.75,
            description="百年老字号小笼包",
            tags=["小笼包", "老字号", "必吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="城隍庙",
            indoor_outdoor="indoor",
            location=Location(lat=31.2273, lng=121.4920),
            ticket_price=30,
        ),
        ScoredPOI(
            name="小杨生煎",
            category="restaurant",
            score=0.7,
            description="上海生煎包代表",
            tags=["生煎", "小吃", "必吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="南京东路",
            indoor_outdoor="indoor",
            location=Location(lat=31.2346, lng=121.4750),
            ticket_price=25,
        ),
        ScoredPOI(
            name="老正兴菜馆",
            category="restaurant",
            score=0.7,
            description="本帮菜老字号",
            tags=["本帮菜", "老字号", "正餐"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="人民广场",
            indoor_outdoor="indoor",
            location=Location(lat=31.2283, lng=121.4453),
            ticket_price=100,
        ),
        ScoredPOI(
            name="新天地美食",
            category="restaurant",
            score=0.7,
            description="时尚餐饮聚集地",
            tags=["西餐", "时尚", "社交"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="新天地",
            indoor_outdoor="indoor",
            location=Location(lat=31.2225, lng=121.4753),
            ticket_price=150,
        ),
        ScoredPOI(
            name="云南路美食街",
            category="restaurant",
            score=0.7,
            description="老字号小吃街",
            tags=["小吃", "美食街", "传统"],
            best_time="晚餐",
            recommended_hours="1小时",
            area="云南路",
            indoor_outdoor="outdoor",
            location=Location(lat=31.2268, lng=121.4829),
            ticket_price=50,
        ),
    ],
    "北京": [
        ScoredPOI(
            name="故宫",
            category="attraction",
            score=0.95,
            description="明清皇宫，世界文化遗产",
            tags=["历史", "文化", "皇家"],
            best_time="上午",
            recommended_hours="半天",
            area="东城区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9160, lng=116.3972),
            ticket_price=60,
        ),
        ScoredPOI(
            name="长城（八达岭）",
            category="attraction",
            score=0.95,
            description="世界七大奇迹之一",
            tags=["历史", "户外", "徒步"],
            best_time="上午",
            recommended_hours="半天",
            area="延庆区",
            indoor_outdoor="outdoor",
            location=Location(lat=40.3544, lng=116.0199),
            ticket_price=40,
        ),
        ScoredPOI(
            name="天坛",
            category="attraction",
            score=0.85,
            description="明清代帝王祭天场所",
            tags=["历史", "文化", "建筑"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="东城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.8822, lng=116.4066),
            ticket_price=15,
        ),
        ScoredPOI(
            name="颐和园",
            category="attraction",
            score=0.9,
            description="中国现存最大皇家园林",
            tags=["园林", "历史", "湖景"],
            best_time="上午",
            recommended_hours="半天",
            area="海淀区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9999, lng=116.2755),
            ticket_price=30,
        ),
        ScoredPOI(
            name="798艺术区",
            category="attraction",
            score=0.8,
            description="工业遗址改造的当代艺术区",
            tags=["艺术", "文艺", "拍照"],
            best_time="下午",
            recommended_hours="2-3小时",
            area="朝阳区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9842, lng=116.4957),
            ticket_price=0,
        ),
        ScoredPOI(
            name="南锣鼓巷",
            category="attraction",
            score=0.8,
            description="老北京胡同文化代表",
            tags=["胡同", "美食", "文艺"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="东城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.9372, lng=116.4038),
            ticket_price=0,
        ),
        ScoredPOI(
            name="鸟巢/水立方",
            category="attraction",
            score=0.8,
            description="2008奥运主场馆",
            tags=["现代", "建筑", "地标"],
            best_time="下午",
            recommended_hours="2小时",
            area="朝阳区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9928, lng=116.3880),
            ticket_price=50,
        ),
        ScoredPOI(
            name="雍和宫",
            category="attraction",
            score=0.75,
            description="北京最大藏传佛教寺院",
            tags=["寺庙", "宗教", "文化"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="东城区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9476, lng=116.4176),
            ticket_price=25,
        ),
        ScoredPOI(
            name="什刹海",
            category="attraction",
            score=0.75,
            description="老北京水景胡同区",
            tags=["湖景", "夜生活", "酒吧"],
            best_time="傍晚",
            recommended_hours="1-2小时",
            area="西城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.9367, lng=116.3847),
            ticket_price=0,
        ),
        ScoredPOI(
            name="国家博物馆",
            category="attraction",
            score=0.85,
            description="世界最大博物馆之一",
            tags=["博物馆", "历史", "文化"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9054, lng=116.3976),
            ticket_price=0,
        ),
        ScoredPOI(
            name="恭王府",
            category="attraction",
            score=0.75,
            description="清代王府建筑代表",
            tags=["历史", "园林", "建筑"],
            best_time="上午",
            recommended_hours="2小时",
            area="西城区",
            indoor_outdoor="mixed",
            location=Location(lat=39.9330, lng=116.3833),
            ticket_price=40,
        ),
        ScoredPOI(
            name="景山公园",
            category="attraction",
            score=0.75,
            description="俯瞰故宫全景的最佳位置",
            tags=["观景", "公园", "历史"],
            best_time="傍晚",
            recommended_hours="1小时",
            area="西城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.9240, lng=116.3968),
            ticket_price=2,
        ),
        ScoredPOI(
            name="前门大街",
            category="attraction",
            score=0.7,
            description="老北京商业街",
            tags=["购物", "美食", "传统"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="东城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.8950, lng=116.3978),
            ticket_price=0,
        ),
        ScoredPOI(
            name="北海公园",
            category="attraction",
            score=0.7,
            description="皇家园林，白塔标志",
            tags=["园林", "湖景", "历史"],
            best_time="上午",
            recommended_hours="2小时",
            area="西城区",
            indoor_outdoor="outdoor",
            location=Location(lat=39.9242, lng=116.3894),
            ticket_price=10,
        ),
        ScoredPOI(
            name="全聚德",
            category="restaurant",
            score=0.85,
            description="北京烤鸭百年老店",
            tags=["烤鸭", "老字号", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9168, lng=116.4049),
            ticket_price=200,
        ),
        ScoredPOI(
            name="四季民福",
            category="restaurant",
            score=0.8,
            description="口碑烤鸭店",
            tags=["烤鸭", "性价比", "排队"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9160, lng=116.4084),
            ticket_price=150,
        ),
        ScoredPOI(
            name="护国寺小吃",
            category="restaurant",
            score=0.7,
            description="老北京传统小吃集合",
            tags=["小吃", "传统", "早餐"],
            best_time="早餐",
            recommended_hours="1小时",
            area="西城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9345, lng=116.3761),
            ticket_price=30,
        ),
        ScoredPOI(
            name="方砖厂炸酱面",
            category="restaurant",
            score=0.7,
            description="老北京炸酱面",
            tags=["炸酱面", "老北京", "小吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9362, lng=116.4061),
            ticket_price=35,
        ),
        ScoredPOI(
            name="姚记炒肝",
            category="restaurant",
            score=0.7,
            description="北京特色小吃",
            tags=["炒肝", "小吃", "传统"],
            best_time="早餐",
            recommended_hours="1小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9372, lng=116.4038),
            ticket_price=25,
        ),
        ScoredPOI(
            name="四季民福烤鸭",
            category="restaurant",
            score=0.85,
            description="北京烤鸭性价比之选",
            tags=["烤鸭", "老字号", "排队"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="东城区",
            indoor_outdoor="indoor",
            location=Location(lat=39.9160, lng=116.3972),
            ticket_price=180,
        ),
    ],
    "广州": [
        ScoredPOI(
            name="广州塔",
            category="attraction",
            score=0.9,
            description="广州地标，600米高空观景",
            tags=["地标", "观景", "夜景"],
            best_time="傍晚",
            recommended_hours="2小时",
            area="海珠区",
            indoor_outdoor="mixed",
            location=Location(lat=23.1090, lng=113.3240),
            ticket_price=150,
        ),
        ScoredPOI(
            name="陈家祠",
            category="attraction",
            score=0.85,
            description="岭南建筑艺术博物馆",
            tags=["历史", "建筑", "文化"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="荔湾区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1300, lng=113.2460),
            ticket_price=10,
        ),
        ScoredPOI(
            name="沙面",
            category="attraction",
            score=0.8,
            description="欧式建筑群，拍照圣地",
            tags=["建筑", "拍照", "历史"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="荔湾区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1100, lng=113.2400),
            ticket_price=0,
        ),
        ScoredPOI(
            name="北京路步行街",
            category="attraction",
            score=0.8,
            description="千年古道遗址步行街",
            tags=["购物", "美食", "历史"],
            best_time="下午",
            recommended_hours="2小时",
            area="越秀区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1250, lng=113.2700),
            ticket_price=0,
        ),
        ScoredPOI(
            name="上下九步行街",
            category="attraction",
            score=0.75,
            description="骑楼风情商业街",
            tags=["骑楼", "美食", "购物"],
            best_time="下午",
            recommended_hours="2小时",
            area="荔湾区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1170, lng=113.2480),
            ticket_price=0,
        ),
        ScoredPOI(
            name="越秀公园",
            category="attraction",
            score=0.7,
            description="广州最大综合性公园",
            tags=["公园", "自然", "地标"],
            best_time="上午",
            recommended_hours="2小时",
            area="越秀区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1400, lng=113.2720),
            ticket_price=0,
        ),
        ScoredPOI(
            name="珠江夜游",
            category="attraction",
            score=0.85,
            description="乘船游览广州夜景",
            tags=["夜景", "游船", "地标"],
            best_time="晚上",
            recommended_hours="1-2小时",
            area="海珠区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1100, lng=113.3200),
            ticket_price=78,
        ),
        ScoredPOI(
            name="广东省博物馆",
            category="attraction",
            score=0.75,
            description="岭南文化综合博物馆",
            tags=["博物馆", "历史", "文化"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="天河区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1170, lng=113.3220),
            ticket_price=0,
        ),
        ScoredPOI(
            name="白云山",
            category="attraction",
            score=0.8,
            description="羊城第一秀，城市绿肺",
            tags=["登山", "自然", "观景"],
            best_time="上午",
            recommended_hours="半天",
            area="白云区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1800, lng=113.2930),
            ticket_price=5,
        ),
        ScoredPOI(
            name="长隆欢乐世界",
            category="attraction",
            score=0.85,
            description="大型主题游乐园",
            tags=["游乐园", "亲子", "刺激"],
            best_time="全天",
            recommended_hours="全天",
            area="番禺区",
            indoor_outdoor="mixed",
            location=Location(lat=23.0030, lng=113.3350),
            ticket_price=250,
        ),
        ScoredPOI(
            name="石室圣心大教堂",
            category="attraction",
            score=0.75,
            description="远东巴黎圣母院",
            tags=["教堂", "建筑", "拍照"],
            best_time="上午",
            recommended_hours="1小时",
            area="越秀区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1170, lng=113.2630),
            ticket_price=0,
        ),
        ScoredPOI(
            name="红砖厂",
            category="attraction",
            score=0.7,
            description="艺术创意园",
            tags=["艺术", "文艺", "拍照"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="天河区",
            indoor_outdoor="mixed",
            location=Location(lat=23.1300, lng=113.3590),
            ticket_price=0,
        ),
        ScoredPOI(
            name="永庆坊",
            category="attraction",
            score=0.75,
            description="西关风情文创街区",
            tags=["文创", "历史", "拍照"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="荔湾区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1170, lng=113.2400),
            ticket_price=0,
        ),
        ScoredPOI(
            name="花城广场",
            category="attraction",
            score=0.7,
            description="CBD中轴城市广场",
            tags=["现代", "地标", "夜景"],
            best_time="傍晚",
            recommended_hours="1-2小时",
            area="天河区",
            indoor_outdoor="outdoor",
            location=Location(lat=23.1190, lng=113.3240),
            ticket_price=0,
        ),
        ScoredPOI(
            name="点都德",
            category="restaurant",
            score=0.85,
            description="广州早茶代表",
            tags=["早茶", "点心", "必吃"],
            best_time="早餐",
            recommended_hours="1.5小时",
            area="越秀区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1291, lng=113.2644),
            ticket_price=80,
        ),
        ScoredPOI(
            name="陶陶居",
            category="restaurant",
            score=0.8,
            description="百年老字号早茶",
            tags=["早茶", "老字号", "点心"],
            best_time="早餐",
            recommended_hours="1.5小时",
            area="荔湾区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1170, lng=113.2460),
            ticket_price=90,
        ),
        ScoredPOI(
            name="广州酒家",
            category="restaurant",
            score=0.8,
            description="正宗粤菜代表",
            tags=["粤菜", "老字号", "正餐"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="荔湾区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1190, lng=113.2440),
            ticket_price=120,
        ),
        ScoredPOI(
            name="银记肠粉",
            category="restaurant",
            score=0.75,
            description="老字号肠粉",
            tags=["肠粉", "小吃", "老字号"],
            best_time="早餐",
            recommended_hours="1小时",
            area="越秀区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1250, lng=113.2700),
            ticket_price=20,
        ),
        ScoredPOI(
            name="陈添记",
            category="restaurant",
            score=0.75,
            description="顺德鱼皮老字号",
            tags=["鱼皮", "小吃", "老字号"],
            best_time="午餐",
            recommended_hours="1小时",
            area="荔湾区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1170, lng=113.2400),
            ticket_price=25,
        ),
        ScoredPOI(
            name="惠食佳",
            category="restaurant",
            score=0.8,
            description="米其林推荐啫啫煲",
            tags=["啫啫煲", "米其林", "粤菜"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="越秀区",
            indoor_outdoor="indoor",
            location=Location(lat=23.1291, lng=113.2644),
            ticket_price=130,
        ),
    ],
    "成都": [
        ScoredPOI(
            name="宽窄巷子",
            category="attraction",
            score=0.85,
            description="清代古街区，成都文化名片",
            tags=["历史", "文化", "美食"],
            best_time="下午",
            recommended_hours="2小时",
            area="青羊区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6600, lng=104.0480),
            ticket_price=0,
        ),
        ScoredPOI(
            name="锦里",
            category="attraction",
            score=0.8,
            description="三国文化古街",
            tags=["历史", "美食", "夜景"],
            best_time="傍晚",
            recommended_hours="2小时",
            area="武侯区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6470, lng=104.0485),
            ticket_price=0,
        ),
        ScoredPOI(
            name="大熊猫繁育基地",
            category="attraction",
            score=0.95,
            description="近距离看国宝大熊猫",
            tags=["亲子", "自然", "必去"],
            best_time="上午",
            recommended_hours="3-4小时",
            area="成华区",
            indoor_outdoor="mixed",
            location=Location(lat=30.7400, lng=104.1430),
            ticket_price=55,
        ),
        ScoredPOI(
            name="武侯祠",
            category="attraction",
            score=0.85,
            description="三国文化圣地",
            tags=["历史", "三国", "文化"],
            best_time="上午",
            recommended_hours="2小时",
            area="武侯区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6450, lng=104.0470),
            ticket_price=50,
        ),
        ScoredPOI(
            name="杜甫草堂",
            category="attraction",
            score=0.8,
            description="诗圣杜甫故居",
            tags=["文学", "园林", "历史"],
            best_time="上午",
            recommended_hours="2小时",
            area="青羊区",
            indoor_outdoor="mixed",
            location=Location(lat=30.6560, lng=104.0260),
            ticket_price=50,
        ),
        ScoredPOI(
            name="春熙路",
            category="attraction",
            score=0.75,
            description="成都最繁华商业街",
            tags=["购物", "美食", "时尚"],
            best_time="下午",
            recommended_hours="2小时",
            area="锦江区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6560, lng=104.0800),
            ticket_price=0,
        ),
        ScoredPOI(
            name="青城山",
            category="attraction",
            score=0.9,
            description="道教名山，世界文化遗产",
            tags=["登山", "自然", "道教"],
            best_time="上午",
            recommended_hours="半天",
            area="都江堰市",
            indoor_outdoor="outdoor",
            location=Location(lat=30.9000, lng=103.5700),
            ticket_price=85,
        ),
        ScoredPOI(
            name="都江堰",
            category="attraction",
            score=0.9,
            description="世界水利文化奇迹",
            tags=["历史", "工程", "自然"],
            best_time="上午",
            recommended_hours="半天",
            area="都江堰市",
            indoor_outdoor="outdoor",
            location=Location(lat=30.9880, lng=103.6170),
            ticket_price=80,
        ),
        ScoredPOI(
            name="人民公园",
            category="attraction",
            score=0.7,
            description="体验成都慢生活",
            tags=["公园", "茶文化", "休闲"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="青羊区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6580, lng=104.0540),
            ticket_price=0,
        ),
        ScoredPOI(
            name="文殊院",
            category="attraction",
            score=0.75,
            description="千年古刹，禅茶一味",
            tags=["寺庙", "素食", "茶文化"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="青羊区",
            indoor_outdoor="mixed",
            location=Location(lat=30.6730, lng=104.0650),
            ticket_price=0,
        ),
        ScoredPOI(
            name="九眼桥",
            category="attraction",
            score=0.7,
            description="成都夜生活地标",
            tags=["夜景", "酒吧", "夜生活"],
            best_time="晚上",
            recommended_hours="1-2小时",
            area="武侯区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6400, lng=104.0850),
            ticket_price=0,
        ),
        ScoredPOI(
            name="太古里",
            category="attraction",
            score=0.8,
            description="现代与传统融合的时尚地标",
            tags=["购物", "时尚", "建筑"],
            best_time="下午",
            recommended_hours="2小时",
            area="锦江区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.6550, lng=104.0830),
            ticket_price=0,
        ),
        ScoredPOI(
            name="金沙遗址",
            category="attraction",
            score=0.8,
            description="古蜀文明遗址",
            tags=["历史", "考古", "博物馆"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="青羊区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6830, lng=104.0130),
            ticket_price=70,
        ),
        ScoredPOI(
            name="蜀大侠火锅",
            category="restaurant",
            score=0.8,
            description="成都网红火锅",
            tags=["火锅", "麻辣", "网红"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="锦江区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6560, lng=104.0800),
            ticket_price=100,
        ),
        ScoredPOI(
            name="小龙坎",
            category="restaurant",
            score=0.85,
            description="重庆火锅成都标杆",
            tags=["火锅", "麻辣", "排队"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="锦江区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6520, lng=104.0780),
            ticket_price=120,
        ),
        ScoredPOI(
            name="陈麻婆豆腐",
            category="restaurant",
            score=0.75,
            description="麻婆豆腐发源地",
            tags=["川菜", "老字号", "经典"],
            best_time="午餐",
            recommended_hours="1小时",
            area="青羊区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6600, lng=104.0480),
            ticket_price=60,
        ),
        ScoredPOI(
            name="钟水饺",
            category="restaurant",
            score=0.7,
            description="成都名小吃",
            tags=["水饺", "小吃", "传统"],
            best_time="午餐",
            recommended_hours="1小时",
            area="青羊区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6600, lng=104.0480),
            ticket_price=20,
        ),
        ScoredPOI(
            name="龙抄手",
            category="restaurant",
            score=0.7,
            description="成都特色抄手",
            tags=["抄手", "小吃", "传统"],
            best_time="午餐",
            recommended_hours="1小时",
            area="锦江区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6560, lng=104.0800),
            ticket_price=25,
        ),
        ScoredPOI(
            name="皇城老妈",
            category="restaurant",
            score=0.8,
            description="成都高端火锅代表",
            tags=["火锅", "高端", "环境好"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="武侯区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6470, lng=104.0485),
            ticket_price=180,
        ),
        ScoredPOI(
            name="叶婆婆钵钵鸡",
            category="restaurant",
            score=0.75,
            description="冷串串人气王",
            tags=["钵钵鸡", "冷串", "小吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="锦江区",
            indoor_outdoor="indoor",
            location=Location(lat=30.6560, lng=104.0800),
            ticket_price=40,
        ),
    ],
    "杭州": [
        ScoredPOI(
            name="西湖",
            category="attraction",
            score=0.95,
            description="世界文化遗产，杭州灵魂",
            tags=["湖景", "自然", "必去"],
            best_time="全天",
            recommended_hours="半天",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2460, lng=120.1460),
            ticket_price=0,
        ),
        ScoredPOI(
            name="灵隐寺",
            category="attraction",
            score=0.9,
            description="千年古刹，佛教圣地",
            tags=["寺庙", "佛教", "文化"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="西湖区",
            indoor_outdoor="mixed",
            location=Location(lat=30.2540, lng=120.1050),
            ticket_price=75,
        ),
        ScoredPOI(
            name="宋城",
            category="attraction",
            score=0.8,
            description="宋代文化主题公园",
            tags=["演出", "历史", "亲子"],
            best_time="全天",
            recommended_hours="半天",
            area="西湖区",
            indoor_outdoor="mixed",
            location=Location(lat=30.1700, lng=120.0990),
            ticket_price=320,
        ),
        ScoredPOI(
            name="西溪湿地",
            category="attraction",
            score=0.85,
            description="城市湿地公园",
            tags=["自然", "舟游", "生态"],
            best_time="上午",
            recommended_hours="半天",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2700, lng=120.0590),
            ticket_price=80,
        ),
        ScoredPOI(
            name="河坊街",
            category="attraction",
            score=0.75,
            description="杭州历史文化街区",
            tags=["美食", "购物", "历史"],
            best_time="下午",
            recommended_hours="2小时",
            area="上城区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2410, lng=120.1710),
            ticket_price=0,
        ),
        ScoredPOI(
            name="千岛湖",
            category="attraction",
            score=0.9,
            description="湖光山色，世外桃源",
            tags=["自然", "湖景", "度假"],
            best_time="全天",
            recommended_hours="全天",
            area="淳安县",
            indoor_outdoor="outdoor",
            location=Location(lat=29.6000, lng=119.0400),
            ticket_price=130,
        ),
        ScoredPOI(
            name="龙井村",
            category="attraction",
            score=0.8,
            description="龙井茶发源地",
            tags=["茶文化", "自然", "体验"],
            best_time="上午",
            recommended_hours="2小时",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2260, lng=120.1150),
            ticket_price=0,
        ),
        ScoredPOI(
            name="断桥残雪",
            category="attraction",
            score=0.85,
            description="西湖十景之一",
            tags=["湖景", "浪漫", "拍照"],
            best_time="全天",
            recommended_hours="1小时",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2560, lng=120.1570),
            ticket_price=0,
        ),
        ScoredPOI(
            name="雷峰塔",
            category="attraction",
            score=0.8,
            description="西湖标志性建筑",
            tags=["历史", "湖景", "地标"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="西湖区",
            indoor_outdoor="indoor",
            location=Location(lat=30.2310, lng=120.1450),
            ticket_price=40,
        ),
        ScoredPOI(
            name="三潭印月",
            category="attraction",
            score=0.85,
            description="西湖第一胜境",
            tags=["湖景", "拍照", "必去"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2370, lng=120.1460),
            ticket_price=20,
        ),
        ScoredPOI(
            name="梅家坞",
            category="attraction",
            score=0.7,
            description="茶文化村",
            tags=["茶文化", "农家乐", "休闲"],
            best_time="上午",
            recommended_hours="2小时",
            area="西湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=30.2180, lng=120.1100),
            ticket_price=0,
        ),
        ScoredPOI(
            name="楼外楼",
            category="restaurant",
            score=0.85,
            description="西湖醋鱼正宗",
            tags=["杭帮菜", "老字号", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="西湖区",
            indoor_outdoor="indoor",
            location=Location(lat=30.2460, lng=120.1460),
            ticket_price=150,
        ),
        ScoredPOI(
            name="知味小笼",
            category="restaurant",
            score=0.75,
            description="杭州小笼包代表",
            tags=["小笼包", "小吃", "老字号"],
            best_time="早餐",
            recommended_hours="1小时",
            area="上城区",
            indoor_outdoor="indoor",
            location=Location(lat=30.2410, lng=120.1710),
            ticket_price=30,
        ),
        ScoredPOI(
            name="外婆家",
            category="restaurant",
            score=0.75,
            description="杭帮菜连锁",
            tags=["杭帮菜", "性价比", "排队"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="西湖区",
            indoor_outdoor="indoor",
            location=Location(lat=30.2460, lng=120.1460),
            ticket_price=80,
        ),
        ScoredPOI(
            name="张生记",
            category="restaurant",
            score=0.7,
            description="老牌杭帮菜",
            tags=["杭帮菜", "老鸭煲", "传统"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="下城区",
            indoor_outdoor="indoor",
            location=Location(lat=30.2700, lng=120.1700),
            ticket_price=100,
        ),
    ],
    "西安": [
        ScoredPOI(
            name="兵马俑",
            category="attraction",
            score=0.95,
            description="世界第八大奇迹",
            tags=["历史", "必去", "世界遗产"],
            best_time="上午",
            recommended_hours="半天",
            area="临潼区",
            indoor_outdoor="indoor",
            location=Location(lat=34.3850, lng=109.2730),
            ticket_price=120,
        ),
        ScoredPOI(
            name="大雁塔",
            category="attraction",
            score=0.9,
            description="唐代佛塔，西安地标",
            tags=["历史", "佛教", "地标"],
            best_time="上午",
            recommended_hours="2小时",
            area="雁塔区",
            indoor_outdoor="mixed",
            location=Location(lat=34.2190, lng=108.9620),
            ticket_price=50,
        ),
        ScoredPOI(
            name="古城墙",
            category="attraction",
            score=0.9,
            description="中国保存最完整古城墙",
            tags=["历史", "骑行", "观景"],
            best_time="下午",
            recommended_hours="2-3小时",
            area="碑林区",
            indoor_outdoor="outdoor",
            location=Location(lat=34.2540, lng=108.9470),
            ticket_price=54,
        ),
        ScoredPOI(
            name="回民街",
            category="attraction",
            score=0.85,
            description="西北美食街，吃货天堂",
            tags=["美食", "小吃", "热闹"],
            best_time="晚上",
            recommended_hours="2小时",
            area="莲湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=34.2640, lng=108.9400),
            ticket_price=0,
        ),
        ScoredPOI(
            name="华清宫",
            category="attraction",
            score=0.8,
            description="唐代皇家温泉行宫",
            tags=["历史", "温泉", "园林"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="临潼区",
            indoor_outdoor="mixed",
            location=Location(lat=34.3590, lng=109.2140),
            ticket_price=120,
        ),
        ScoredPOI(
            name="大唐芙蓉园",
            category="attraction",
            score=0.8,
            description="盛唐文化主题公园",
            tags=["园林", "演出", "夜景"],
            best_time="下午",
            recommended_hours="3-4小时",
            area="雁塔区",
            indoor_outdoor="mixed",
            location=Location(lat=34.2110, lng=108.9730),
            ticket_price=120,
        ),
        ScoredPOI(
            name="陕西历史博物馆",
            category="attraction",
            score=0.9,
            description="华夏珍宝库",
            tags=["博物馆", "历史", "必去"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="雁塔区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2170, lng=108.9550),
            ticket_price=0,
        ),
        ScoredPOI(
            name="钟楼",
            category="attraction",
            score=0.8,
            description="西安城市中心地标",
            tags=["地标", "历史", "建筑"],
            best_time="傍晚",
            recommended_hours="1小时",
            area="碑林区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2600, lng=108.9430),
            ticket_price=30,
        ),
        ScoredPOI(
            name="鼓楼",
            category="attraction",
            score=0.75,
            description="明代鼓楼建筑",
            tags=["历史", "建筑", "music"],
            best_time="下午",
            recommended_hours="1小时",
            area="碑林区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2610, lng=108.9390),
            ticket_price=30,
        ),
        ScoredPOI(
            name="小雁塔",
            category="attraction",
            score=0.75,
            description="唐代密檐式砖塔",
            tags=["历史", "佛教", "安静"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="碑林区",
            indoor_outdoor="outdoor",
            location=Location(lat=34.2410, lng=108.9370),
            ticket_price=0,
        ),
        ScoredPOI(
            name="肉夹馍",
            category="restaurant",
            score=0.9,
            description="西安美食名片",
            tags=["小吃", "必吃", "面食"],
            best_time="午餐",
            recommended_hours="1小时",
            area="碑林区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2600, lng=108.9430),
            ticket_price=15,
        ),
        ScoredPOI(
            name="羊肉泡馍",
            category="restaurant",
            score=0.85,
            description="西安经典美食",
            tags=["面食", "羊肉", "必吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="莲湖区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2640, lng=108.9400),
            ticket_price=35,
        ),
        ScoredPOI(
            name="凉皮",
            category="restaurant",
            score=0.8,
            description="西安夏日必吃",
            tags=["小吃", "面食", "凉爽"],
            best_time="午餐",
            recommended_hours="1小时",
            area="碑林区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2540, lng=108.9470),
            ticket_price=10,
        ),
        ScoredPOI(
            name="德发长饺子馆",
            category="restaurant",
            score=0.75,
            description="饺子宴老字号",
            tags=["饺子", "老字号", "特色"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="莲湖区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2640, lng=108.9400),
            ticket_price=80,
        ),
        ScoredPOI(
            name="长安大排档",
            category="restaurant",
            score=0.8,
            description="陕菜文化体验",
            tags=["陕菜", "氛围", "网红"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="雁塔区",
            indoor_outdoor="indoor",
            location=Location(lat=34.2170, lng=108.9550),
            ticket_price=100,
        ),
    ],
    "重庆": [
        ScoredPOI(
            name="洪崖洞",
            category="attraction",
            score=0.9,
            description="现实版千与千寻",
            tags=["夜景", "建筑", "必去"],
            best_time="晚上",
            recommended_hours="2小时",
            area="渝中区",
            indoor_outdoor="mixed",
            location=Location(lat=29.5630, lng=106.5810),
            ticket_price=0,
        ),
        ScoredPOI(
            name="解放碑",
            category="attraction",
            score=0.8,
            description="重庆商业中心地标",
            tags=["地标", "购物", "美食"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="渝中区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.5600, lng=106.5730),
            ticket_price=0,
        ),
        ScoredPOI(
            name="磁器口",
            category="attraction",
            score=0.8,
            description="千年古镇，美食街",
            tags=["古镇", "美食", "文化"],
            best_time="下午",
            recommended_hours="2-3小时",
            area="沙坪坝区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.5830, lng=106.4500),
            ticket_price=0,
        ),
        ScoredPOI(
            name="长江索道",
            category="attraction",
            score=0.85,
            description="空中穿越长江",
            tags=["交通", "观景", "体验"],
            best_time="白天",
            recommended_hours="1小时",
            area="渝中区",
            indoor_outdoor="mixed",
            location=Location(lat=29.5510, lng=106.5850),
            ticket_price=20,
        ),
        ScoredPOI(
            name="武隆天坑",
            category="attraction",
            score=0.9,
            description="世界自然遗产",
            tags=["自然", "户外", "电影取景"],
            best_time="全天",
            recommended_hours="全天",
            area="武隆区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.3900, lng=107.7800),
            ticket_price=135,
        ),
        ScoredPOI(
            name="朝天门",
            category="attraction",
            score=0.75,
            description="长江嘉陵江交汇处",
            tags=["江景", "地标", "历史"],
            best_time="傍晚",
            recommended_hours="1小时",
            area="渝中区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.5680, lng=106.5860),
            ticket_price=0,
        ),
        ScoredPOI(
            name="鹅岭二厂",
            category="attraction",
            score=0.75,
            description="文创园区",
            tags=["文创", "拍照", "文艺"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="渝中区",
            indoor_outdoor="mixed",
            location=Location(lat=29.5490, lng=106.5490),
            ticket_price=0,
        ),
        ScoredPOI(
            name="四川美术学院",
            category="attraction",
            score=0.7,
            description="涂鸦街打卡地",
            tags=["艺术", "涂鸦", "拍照"],
            best_time="下午",
            recommended_hours="1小时",
            area="九龙坡区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.4880, lng=106.5180),
            ticket_price=0,
        ),
        ScoredPOI(
            name="南山一棵树",
            category="attraction",
            score=0.8,
            description="俯瞰重庆夜景",
            tags=["夜景", "观景", "拍照"],
            best_time="晚上",
            recommended_hours="1小时",
            area="南岸区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.5480, lng=106.6010),
            ticket_price=30,
        ),
        ScoredPOI(
            name="大足石刻",
            category="attraction",
            score=0.85,
            description="世界文化遗产石窟",
            tags=["石刻", "佛教", "世界遗产"],
            best_time="上午",
            recommended_hours="半天",
            area="大足区",
            indoor_outdoor="outdoor",
            location=Location(lat=29.7300, lng=105.7400),
            ticket_price=135,
        ),
        ScoredPOI(
            name="重庆火锅",
            category="restaurant",
            score=0.9,
            description="重庆美食灵魂",
            tags=["火锅", "麻辣", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="渝中区",
            indoor_outdoor="indoor",
            location=Location(lat=29.5630, lng=106.5516),
            ticket_price=90,
        ),
        ScoredPOI(
            name="小面",
            category="restaurant",
            score=0.85,
            description="重庆人早餐标配",
            tags=["面食", "早餐", "麻辣"],
            best_time="早餐",
            recommended_hours="1小时",
            area="渝中区",
            indoor_outdoor="indoor",
            location=Location(lat=29.5630, lng=106.5516),
            ticket_price=12,
        ),
        ScoredPOI(
            name="酸辣粉",
            category="restaurant",
            score=0.8,
            description="重庆街边经典",
            tags=["小吃", "麻辣", "街边"],
            best_time="午餐",
            recommended_hours="1小时",
            area="渝中区",
            indoor_outdoor="indoor",
            location=Location(lat=29.5630, lng=106.5516),
            ticket_price=10,
        ),
        ScoredPOI(
            name="李子坝梁山鸡",
            category="restaurant",
            score=0.8,
            description="重庆江湖菜代表",
            tags=["江湖菜", "鸡肉", "麻辣"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="渝中区",
            indoor_outdoor="indoor",
            location=Location(lat=29.5490, lng=106.5340),
            ticket_price=100,
        ),
    ],
    "深圳": [
        ScoredPOI(
            name="世界之窗",
            category="attraction",
            score=0.8,
            description="微缩世界景观公园",
            tags=["主题公园", "亲子", "娱乐"],
            best_time="全天",
            recommended_hours="半天",
            area="南山区",
            indoor_outdoor="mixed",
            location=Location(lat=22.5370, lng=113.9700),
            ticket_price=220,
        ),
        ScoredPOI(
            name="欢乐谷",
            category="attraction",
            score=0.8,
            description="大型现代主题乐园",
            tags=["游乐园", "亲子", "刺激"],
            best_time="全天",
            recommended_hours="全天",
            area="南山区",
            indoor_outdoor="mixed",
            location=Location(lat=22.5450, lng=113.9800),
            ticket_price=230,
        ),
        ScoredPOI(
            name="大梅沙",
            category="attraction",
            score=0.75,
            description="深圳最受欢迎海滩",
            tags=["海滩", "游泳", "度假"],
            best_time="上午",
            recommended_hours="半天",
            area="盐田区",
            indoor_outdoor="outdoor",
            location=Location(lat=22.5900, lng=114.3130),
            ticket_price=0,
        ),
        ScoredPOI(
            name="华侨城",
            category="attraction",
            score=0.8,
            description="文化创意主题园区",
            tags=["文创", "艺术", "亲子"],
            best_time="全天",
            recommended_hours="3-4小时",
            area="南山区",
            indoor_outdoor="mixed",
            location=Location(lat=22.5431, lng=113.9810),
            ticket_price=0,
        ),
        ScoredPOI(
            name="深圳湾公园",
            category="attraction",
            score=0.75,
            description="城市海滨长廊",
            tags=["海滨", "骑行", "散步"],
            best_time="傍晚",
            recommended_hours="2小时",
            area="南山区",
            indoor_outdoor="outdoor",
            location=Location(lat=22.5180, lng=113.9600),
            ticket_price=0,
        ),
        ScoredPOI(
            name="莲花山公园",
            category="attraction",
            score=0.7,
            description="瞻仰邓小平铜像",
            tags=["公园", "观景", "红色"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="福田区",
            indoor_outdoor="outdoor",
            location=Location(lat=22.5510, lng=114.0550),
            ticket_price=0,
        ),
        ScoredPOI(
            name="东门老街",
            category="attraction",
            score=0.7,
            description="深圳老商业街",
            tags=["购物", "美食", "历史"],
            best_time="下午",
            recommended_hours="2小时",
            area="罗湖区",
            indoor_outdoor="outdoor",
            location=Location(lat=22.5460, lng=114.1180),
            ticket_price=0,
        ),
        ScoredPOI(
            name="海上世界",
            category="attraction",
            score=0.75,
            description="明华轮地标片区",
            tags=["餐饮", "夜景", "地标"],
            best_time="晚上",
            recommended_hours="2小时",
            area="南山区",
            indoor_outdoor="mixed",
            location=Location(lat=22.4950, lng=113.9120),
            ticket_price=0,
        ),
        ScoredPOI(
            name="大鹏所城",
            category="attraction",
            score=0.7,
            description="明清海防古城",
            tags=["历史", "古镇", "海滩"],
            best_time="上午",
            recommended_hours="2小时",
            area="大鹏新区",
            indoor_outdoor="outdoor",
            location=Location(lat=22.5900, lng=114.4800),
            ticket_price=20,
        ),
        ScoredPOI(
            name="深圳博物馆",
            category="attraction",
            score=0.65,
            description="了解深圳发展史",
            tags=["博物馆", "历史", "免费"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="福田区",
            indoor_outdoor="indoor",
            location=Location(lat=22.5470, lng=114.0600),
            ticket_price=0,
        ),
        ScoredPOI(
            name="潮汕牛肉火锅",
            category="restaurant",
            score=0.85,
            description="手打牛肉丸火锅",
            tags=["火锅", "潮汕", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="福田区",
            indoor_outdoor="indoor",
            location=Location(lat=22.5431, lng=114.0579),
            ticket_price=100,
        ),
        ScoredPOI(
            name="椰子鸡",
            category="restaurant",
            score=0.8,
            description="深圳特色火锅",
            tags=["火锅", "椰子", "清爽"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="南山区",
            indoor_outdoor="indoor",
            location=Location(lat=22.5431, lng=114.0579),
            ticket_price=120,
        ),
        ScoredPOI(
            name="肠粉",
            category="restaurant",
            score=0.75,
            description="广东经典早餐",
            tags=["早餐", "小吃", "粤式"],
            best_time="早餐",
            recommended_hours="1小时",
            area="罗湖区",
            indoor_outdoor="indoor",
            location=Location(lat=22.5431, lng=114.0579),
            ticket_price=15,
        ),
    ],
    "南京": [
        ScoredPOI(
            name="中山陵",
            category="attraction",
            score=0.9,
            description="孙中山先生陵寝",
            tags=["历史", "建筑", "红色"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="玄武区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0603, lng=118.8500),
            ticket_price=0,
        ),
        ScoredPOI(
            name="夫子庙",
            category="attraction",
            score=0.8,
            description="南京文化地标",
            tags=["文化", "美食", "购物"],
            best_time="下午",
            recommended_hours="2小时",
            area="秦淮区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0200, lng=118.7890),
            ticket_price=0,
        ),
        ScoredPOI(
            name="秦淮河",
            category="attraction",
            score=0.85,
            description="六朝金粉，桨声灯影",
            tags=["夜景", "游船", "浪漫"],
            best_time="晚上",
            recommended_hours="1-2小时",
            area="秦淮区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0180, lng=118.7950),
            ticket_price=80,
        ),
        ScoredPOI(
            name="明孝陵",
            category="attraction",
            score=0.85,
            description="明代开国皇帝陵墓",
            tags=["历史", "世界遗产", "建筑"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="玄武区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0580, lng=118.8540),
            ticket_price=70,
        ),
        ScoredPOI(
            name="总统府",
            category="attraction",
            score=0.8,
            description="中国近代史见证",
            tags=["历史", "建筑", "政治"],
            best_time="上午",
            recommended_hours="2小时",
            area="玄武区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0460, lng=118.7970),
            ticket_price=40,
        ),
        ScoredPOI(
            name="鸡鸣寺",
            category="attraction",
            score=0.75,
            description="南朝第一寺",
            tags=["寺庙", "樱花", "历史"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="玄武区",
            indoor_outdoor="mixed",
            location=Location(lat=32.0620, lng=118.7940),
            ticket_price=10,
        ),
        ScoredPOI(
            name="玄武湖",
            category="attraction",
            score=0.75,
            description="金陵明珠",
            tags=["湖景", "公园", "休闲"],
            best_time="下午",
            recommended_hours="2小时",
            area="玄武区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0720, lng=118.7970),
            ticket_price=0,
        ),
        ScoredPOI(
            name="南京博物院",
            category="attraction",
            score=0.85,
            description="中国三大博物馆之一",
            tags=["博物馆", "历史", "文化"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="玄武区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0410, lng=118.8220),
            ticket_price=0,
        ),
        ScoredPOI(
            name="老门东",
            category="attraction",
            score=0.75,
            description="南京历史文化街区",
            tags=["美食", "历史", "建筑"],
            best_time="下午",
            recommended_hours="2小时",
            area="秦淮区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.0150, lng=118.7910),
            ticket_price=0,
        ),
        ScoredPOI(
            name="栖霞山",
            category="attraction",
            score=0.75,
            description="金陵第一明秀山",
            tags=["登山", "红叶", "寺庙"],
            best_time="上午",
            recommended_hours="半天",
            area="栖霞区",
            indoor_outdoor="outdoor",
            location=Location(lat=32.1560, lng=118.9520),
            ticket_price=40,
        ),
        ScoredPOI(
            name="鸭血粉丝汤",
            category="restaurant",
            score=0.85,
            description="南京美食名片",
            tags=["小吃", "必吃", "传统"],
            best_time="午餐",
            recommended_hours="1小时",
            area="秦淮区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0603, lng=118.7969),
            ticket_price=20,
        ),
        ScoredPOI(
            name="盐水鸭",
            category="restaurant",
            score=0.8,
            description="金陵名菜",
            tags=["凉菜", "传统", "必吃"],
            best_time="晚餐",
            recommended_hours="1小时",
            area="秦淮区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0603, lng=118.7969),
            ticket_price=40,
        ),
        ScoredPOI(
            name="小笼包",
            category="restaurant",
            score=0.8,
            description="南京薄皮小笼",
            tags=["小笼包", "小吃", "甜口"],
            best_time="早餐",
            recommended_hours="1小时",
            area="秦淮区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0603, lng=118.7969),
            ticket_price=20,
        ),
        ScoredPOI(
            name="南京大牌档",
            category="restaurant",
            score=0.85,
            description="金陵风味集合",
            tags=["淮扬菜", "氛围", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="秦淮区",
            indoor_outdoor="indoor",
            location=Location(lat=32.0200, lng=118.7890),
            ticket_price=100,
        ),
    ],
    "厦门": [
        ScoredPOI(
            name="鼓浪屿",
            category="attraction",
            score=0.95,
            description="海上花园，钢琴之岛",
            tags=["海岛", "历史", "必去"],
            best_time="全天",
            recommended_hours="全天",
            area="思明区",
            indoor_outdoor="mixed",
            location=Location(lat=24.4470, lng=118.0660),
            ticket_price=35,
        ),
        ScoredPOI(
            name="南普陀寺",
            category="attraction",
            score=0.85,
            description="闽南佛教圣地",
            tags=["寺庙", "佛教", "素斋"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="思明区",
            indoor_outdoor="mixed",
            location=Location(lat=24.4430, lng=118.0900),
            ticket_price=0,
        ),
        ScoredPOI(
            name="厦门大学",
            category="attraction",
            score=0.8,
            description="中国最美大学",
            tags=["校园", "建筑", "拍照"],
            best_time="上午",
            recommended_hours="1-2小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4380, lng=118.0900),
            ticket_price=0,
        ),
        ScoredPOI(
            name="环岛路",
            category="attraction",
            score=0.8,
            description="最美马拉松赛道",
            tags=["骑行", "海滩", "海景"],
            best_time="下午",
            recommended_hours="2-3小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4340, lng=118.1120),
            ticket_price=0,
        ),
        ScoredPOI(
            name="曾厝垵",
            category="attraction",
            score=0.75,
            description="文艺渔村",
            tags=["小吃", "文艺", "民宿"],
            best_time="下午",
            recommended_hours="2小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4330, lng=118.1120),
            ticket_price=0,
        ),
        ScoredPOI(
            name="中山路步行街",
            category="attraction",
            score=0.75,
            description="厦门商业名片",
            tags=["购物", "美食", "骑楼"],
            best_time="晚上",
            recommended_hours="2小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4540, lng=118.0820),
            ticket_price=0,
        ),
        ScoredPOI(
            name="胡里山炮台",
            category="attraction",
            score=0.7,
            description="清代海防炮台",
            tags=["历史", "军事", "海景"],
            best_time="上午",
            recommended_hours="1小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4320, lng=118.1020),
            ticket_price=25,
        ),
        ScoredPOI(
            name="园林植物园",
            category="attraction",
            score=0.75,
            description="热带植物王国",
            tags=["自然", "植物", "拍照"],
            best_time="上午",
            recommended_hours="半天",
            area="思明区",
            indoor_outdoor="mixed",
            location=Location(lat=24.4490, lng=118.0970),
            ticket_price=40,
        ),
        ScoredPOI(
            name="沙坡尾",
            category="attraction",
            score=0.7,
            description="老厦门避风坞",
            tags=["文艺", "拍照", "咖啡"],
            best_time="下午",
            recommended_hours="1-2小时",
            area="思明区",
            indoor_outdoor="outdoor",
            location=Location(lat=24.4450, lng=118.0790),
            ticket_price=0,
        ),
        ScoredPOI(
            name="沙茶面",
            category="restaurant",
            score=0.85,
            description="厦门味道代表",
            tags=["面食", "小吃", "必吃"],
            best_time="午餐",
            recommended_hours="1小时",
            area="思明区",
            indoor_outdoor="indoor",
            location=Location(lat=24.4540, lng=118.0820),
            ticket_price=20,
        ),
        ScoredPOI(
            name="海蛎煎",
            category="restaurant",
            score=0.8,
            description="闽南经典小吃",
            tags=["海鲜", "小吃", "传统"],
            best_time="午餐",
            recommended_hours="1小时",
            area="思明区",
            indoor_outdoor="indoor",
            location=Location(lat=24.4470, lng=118.0660),
            ticket_price=15,
        ),
        ScoredPOI(
            name="花生汤",
            category="restaurant",
            score=0.75,
            description="厦门古早味甜品",
            tags=["甜品", "早餐", "传统"],
            best_time="早餐",
            recommended_hours="1小时",
            area="思明区",
            indoor_outdoor="indoor",
            location=Location(lat=24.4540, lng=118.0820),
            ticket_price=8,
        ),
        ScoredPOI(
            name="堂宴",
            category="restaurant",
            score=0.8,
            description="厦门私房菜",
            tags=["闽菜", "私房菜", "高端"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="思明区",
            indoor_outdoor="indoor",
            location=Location(lat=24.4540, lng=118.0820),
            ticket_price=150,
        ),
    ],
    "青岛": [
        ScoredPOI(
            name="栈桥",
            category="attraction",
            score=0.85,
            description="青岛城市象征",
            tags=["海景", "历史", "地标"],
            best_time="下午",
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0600, lng=120.3170),
            ticket_price=0,
        ),
        ScoredPOI(
            name="八大关",
            category="attraction",
            score=0.9,
            description="万国建筑博览会",
            tags=["建筑", "拍照", "历史"],
            best_time="上午",
            recommended_hours="2-3小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0520, lng=120.3530),
            ticket_price=0,
        ),
        ScoredPOI(
            name="崂山",
            category="attraction",
            score=0.9,
            description="海上第一名山",
            tags=["登山", "道教", "自然"],
            best_time="全天",
            recommended_hours="全天",
            area="崂山区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.1900, lng=120.6270),
            ticket_price=130,
        ),
        ScoredPOI(
            name="五四广场",
            category="attraction",
            score=0.75,
            description="青岛现代地标",
            tags=["地标", "现代", "夜景"],
            best_time="傍晚",
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0610, lng=120.3840),
            ticket_price=0,
        ),
        ScoredPOI(
            name="青岛啤酒博物馆",
            category="attraction",
            score=0.85,
            description="了解青啤百年历史",
            tags=["博物馆", "啤酒", "体验"],
            best_time="下午",
            recommended_hours="2小时",
            area="市北区",
            indoor_outdoor="indoor",
            location=Location(lat=36.0800, lng=120.3400),
            ticket_price=60,
        ),
        ScoredPOI(
            name="小鱼山",
            category="attraction",
            score=0.75,
            description="俯瞰老城红瓦绿树",
            tags=["观景", "拍照", "公园"],
            best_time="上午",
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0580, lng=120.3350),
            ticket_price=10,
        ),
        ScoredPOI(
            name="信号山公园",
            category="attraction",
            score=0.7,
            description="俯瞰青岛全景",
            tags=["观景", "公园", "地标"],
            best_time="下午",
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0650, lng=120.3280),
            ticket_price=15,
        ),
        ScoredPOI(
            name="金沙滩",
            category="attraction",
            score=0.8,
            description="亚洲第一滩",
            tags=["海滩", "游泳", "度假"],
            best_time="上午",
            recommended_hours="半天",
            area="黄岛区",
            indoor_outdoor="outdoor",
            location=Location(lat=35.9500, lng=120.2300),
            ticket_price=0,
        ),
        ScoredPOI(
            name="劈柴院",
            category="attraction",
            score=0.7,
            description="百年小吃街",
            tags=["美食", "老城区", "传统"],
            best_time="晚上",
            recommended_hours="1-2小时",
            area="市南区",
            indoor_outdoor="outdoor",
            location=Location(lat=36.0670, lng=120.3190),
            ticket_price=0,
        ),
        ScoredPOI(
            name="青岛啤酒",
            category="restaurant",
            score=0.85,
            description="喝正宗青岛散啤",
            tags=["啤酒", "海鲜", "必喝"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="市北区",
            indoor_outdoor="indoor",
            location=Location(lat=36.0800, lng=120.3400),
            ticket_price=80,
        ),
        ScoredPOI(
            name="海鲜大咖",
            category="restaurant",
            score=0.8,
            description="青岛海鲜盛宴",
            tags=["海鲜", "烧烤", "必吃"],
            best_time="晚餐",
            recommended_hours="1.5小时",
            area="市南区",
            indoor_outdoor="indoor",
            location=Location(lat=36.0600, lng=120.3800),
            ticket_price=150,
        ),
        ScoredPOI(
            name="鲅鱼饺子",
            category="restaurant",
            score=0.8,
            description="青岛特色水饺",
            tags=["饺子", "海鲜", "传统"],
            best_time="午餐",
            recommended_hours="1小时",
            area="市南区",
            indoor_outdoor="indoor",
            location=Location(lat=36.0600, lng=120.3800),
            ticket_price=35,
        ),
    ],
}

# Merge extended POI data. This keeps the original file readable while adding
# enough attractions/restaurants to support 5-7 day itineraries.
from skills.city_data_extra import CITY_EXTRA


def _merge_city_extras() -> None:
    for city, extras in CITY_EXTRA.items():
        if city not in CITY_DEFAULTS:
            CITY_DEFAULTS[city] = []
        existing_names = {p.name for p in CITY_DEFAULTS[city]}
        CITY_DEFAULTS[city].extend([p for p in extras if p.name not in existing_names])


_merge_city_extras()
