"""Pydantic models for Planning Core, Rule Validator, and Critic/Repair."""

from typing import Optional, Literal
from pydantic import BaseModel, Field

from schemas import DayPlan, ScoredPOI, WeatherDay, UserProfile, Location


# --------------------------------------------------------------------------- #
# Strategy Models
# --------------------------------------------------------------------------- #


class DayTheme(BaseModel):
    """Theme for a single day."""

    day_number: int
    theme: str
    area_focus: str
    primary_tags: list[str] = Field(default_factory=list)


class AreaGroup(BaseModel):
    """POIs grouped by geographic area."""

    area: str
    poi_names: list[str] = Field(default_factory=list)
    priority_score: float = 0.0


class Strategy(BaseModel):
    """High-level itinerary strategy generated by heuristic or LLM."""

    day_themes: list[DayTheme] = Field(default_factory=list)
    area_groups: list[AreaGroup] = Field(default_factory=list)
    must_see: list[str] = Field(default_factory=list)
    suggested_restaurants: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


# --------------------------------------------------------------------------- #
# Rule Validator Models
# --------------------------------------------------------------------------- #


class RuleViolation(BaseModel):
    """A single rule violation with severity classification."""

    rule: str
    severity: Literal["hard", "soft"]
    message: str
    day_number: Optional[int] = None
    activity_index: Optional[int] = None
    poi_name: Optional[str] = None
    suggested_fix: Optional[dict] = None


class ValidationReport(BaseModel):
    """Complete validation result for an itinerary draft."""

    hard_violations: list[RuleViolation] = Field(default_factory=list)
    soft_warnings: list[RuleViolation] = Field(default_factory=list)
    passed: bool = False

    def __bool__(self) -> bool:
        return self.passed


# --------------------------------------------------------------------------- #
# Critic / Repair Models
# --------------------------------------------------------------------------- #


class RepairPlan(BaseModel):
    """Machine-executable repair plan."""

    action: Literal["swap", "move", "insert", "remove", "split", "merge"]
    target: dict = Field(default_factory=dict)
    params: dict = Field(default_factory=dict)
    reason: str = ""


class RepairResult(BaseModel):
    """Result of applying a repair plan."""

    success: bool = False
    applied_plans: list[RepairPlan] = Field(default_factory=list)
    rejected_plans: list[RepairPlan] = Field(default_factory=list)
    new_violations: list[RuleViolation] = Field(default_factory=list)
    needs_human: bool = False


# --------------------------------------------------------------------------- #
# Planning Core Output Models
# --------------------------------------------------------------------------- #


class PlanningCoreResult(BaseModel):
    """Result from Planning Core (2A output)."""

    strategy: Strategy
    itinerary_draft: list[DayPlan] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    fallback_used: bool = False


class EnrichedItinerary(BaseModel):
    """Final enriched itinerary with prose (2C output)."""

    itinerary: list[DayPlan] = Field(default_factory=list)
    proposal_text: str = ""
    warnings: list[str] = Field(default_factory=list)
    needs_human: bool = False
