"""step1_schema_alignment_v3_0

Revision ID: 4114fc8f89a7
Revises: h8i9j0k1l2m3
Create Date: 2026-06-18 19:08:55.269109

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401  registers VECTOR type
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4114fc8f89a7"
down_revision: Union[str, Sequence[str], None] = "h8i9j0k1l2m3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spot_distance_multi",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_spot_id", sa.UUID(), nullable=False),
        sa.Column("to_spot_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("time_window", sa.String(length=50), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["from_spot_id"], ["attractions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_spot_id"], ["attractions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_spot_distance_from_to_mode",
        "spot_distance_multi",
        ["from_spot_id", "to_spot_id", "mode"],
        unique=True,
    )
    op.create_index(
        op.f("ix_spot_distance_multi_from_spot_id"),
        "spot_distance_multi",
        ["from_spot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spot_distance_multi_to_spot_id"),
        "spot_distance_multi",
        ["to_spot_id"],
        unique=False,
    )
    op.create_table(
        "user_trip_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("trip_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trip_vector", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_trip_history_user_id"), "user_trip_history", ["user_id"], unique=False
    )
    op.create_table(
        "planning_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("request_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_itinerary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("conflict_reason", sa.Text(), nullable=True),
        sa.Column("modification_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_log_conversation_id"), "planning_log", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_planning_log_user_id"), "planning_log", ["user_id"], unique=False)
    op.create_table(
        "user_modification_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("planning_log_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["planning_log_id"], ["planning_log.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_modification_log_planning_log_id"),
        "user_modification_log",
        ["planning_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_modification_log_user_id"), "user_modification_log", ["user_id"], unique=False
    )
    op.add_column("attractions", sa.Column("min_play_time", sa.Integer(), nullable=True))
    op.add_column("attractions", sa.Column("max_play_time", sa.Integer(), nullable=True))
    op.add_column("attractions", sa.Column("reservation_advance_days", sa.Integer(), nullable=True))
    op.add_column("attractions", sa.Column("queue_time_avg", sa.Integer(), nullable=True))
    op.add_column(
        "attractions",
        sa.Column(
            "accessibility",
            postgresql.JSON(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("attractions", sa.Column("indoor_outdoor", sa.String(length=20), nullable=True))
    op.add_column(
        "attractions", sa.Column("night_open", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "attractions",
        sa.Column("spot_tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
    )
    op.add_column(
        "attractions",
        sa.Column(
            "season_restriction", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "attractions",
        sa.Column(
            "temp_closure_dates", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "attractions",
        sa.Column("description_vector", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    )
    op.add_column("attractions", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True))
    op.create_index(
        "idx_attractions_search",
        "attractions",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_attractions_vector",
        "attractions",
        ["description_vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"description_vector": "vector_cosine_ops"},
    )
    op.add_column(
        "city_info", sa.Column("daily_avg_cost", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column("city_info", sa.Column("recommended_days", sa.Integer(), nullable=True))
    op.add_column("city_info", sa.Column("notes", sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_user_profile_vectors_user_id",
        "user_profile_vectors",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_profile_vectors_user_id", "user_profile_vectors", type_="foreignkey"
    )
    op.drop_column("city_info", "notes")
    op.drop_column("city_info", "recommended_days")
    op.drop_column("city_info", "daily_avg_cost")
    op.drop_index(
        "idx_attractions_vector",
        table_name="attractions",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"description_vector": "vector_cosine_ops"},
    )
    op.drop_index("idx_attractions_search", table_name="attractions", postgresql_using="gin")
    op.drop_column("attractions", "search_vector")
    op.drop_column("attractions", "description_vector")
    op.drop_column("attractions", "temp_closure_dates")
    op.drop_column("attractions", "season_restriction")
    op.drop_column("attractions", "spot_tags")
    op.drop_column("attractions", "night_open")
    op.drop_column("attractions", "indoor_outdoor")
    op.drop_column("attractions", "accessibility")
    op.drop_column("attractions", "queue_time_avg")
    op.drop_column("attractions", "reservation_advance_days")
    op.drop_column("attractions", "max_play_time")
    op.drop_column("attractions", "min_play_time")
    op.drop_index(op.f("ix_user_modification_log_user_id"), table_name="user_modification_log")
    op.drop_index(
        op.f("ix_user_modification_log_planning_log_id"), table_name="user_modification_log"
    )
    op.drop_table("user_modification_log")
    op.drop_index(op.f("ix_planning_log_user_id"), table_name="planning_log")
    op.drop_index(op.f("ix_planning_log_conversation_id"), table_name="planning_log")
    op.drop_table("planning_log")
    op.drop_index(op.f("ix_user_trip_history_user_id"), table_name="user_trip_history")
    op.drop_table("user_trip_history")
    op.drop_index(op.f("ix_spot_distance_multi_to_spot_id"), table_name="spot_distance_multi")
    op.drop_index(op.f("ix_spot_distance_multi_from_spot_id"), table_name="spot_distance_multi")
    op.drop_index("ix_spot_distance_from_to_mode", table_name="spot_distance_multi")
    op.drop_table("spot_distance_multi")
    # ### end Alembic commands ###
