"""initial_prd_schema

Revision ID: 473363b5ea3f
Revises:
Create Date: 2026-06-15 13:29:21.387302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "473363b5ea3f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("state_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_status"), "conversations", ["status"], unique=False)
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index(
        "ix_conversations_user_updated", "conversations", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("personal", sa.JSON(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("frequent_destinations", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "planning_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("user_input", sa.Text(), nullable=True),
        sa.Column("user_uuid", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id_str", sa.String(length=64), nullable=True),
        sa.Column("queue_name", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_requirements", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("stage_timings", sa.JSON(), nullable=True),
        sa.Column("intent_result", sa.JSON(), nullable=True),
        sa.Column("strategy", sa.JSON(), nullable=True),
        sa.Column("itinerary_draft", sa.JSON(), nullable=True),
        sa.Column("itinerary_final", sa.JSON(), nullable=True),
        sa.Column("proposal_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stage", sa.String(length=32), nullable=True),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("user_feedback", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_jobs_conversation_id"), "planning_jobs", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_planning_jobs_conversation_id_str"),
        "planning_jobs",
        ["conversation_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planning_jobs_queue_name"), "planning_jobs", ["queue_name"], unique=False
    )
    op.create_index(
        op.f("ix_planning_jobs_session_id"), "planning_jobs", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_planning_jobs_status"), "planning_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_planning_jobs_user_id"), "planning_jobs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_planning_jobs_user_uuid"), "planning_jobs", ["user_uuid"], unique=False
    )
    op.create_table(
        "itineraries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("proposal_text", sa.Text(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["planning_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itineraries_conversation_id"), "itineraries", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_destination"), "itineraries", ["destination"], unique=False
    )
    op.create_index(op.f("ix_itineraries_job_id"), "itineraries", ["job_id"], unique=False)
    op.create_index(
        "ix_itineraries_user_created", "itineraries", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_itineraries_user_id"), "itineraries", ["user_id"], unique=False)
    op.create_table(
        "planning_job_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["planning_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_job_events_job_id"), "planning_job_events", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_planning_job_events_job_id"), table_name="planning_job_events")
    op.drop_table("planning_job_events")
    op.drop_index(op.f("ix_itineraries_user_id"), table_name="itineraries")
    op.drop_index("ix_itineraries_user_created", table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_job_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_conversation_id"), table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index(op.f("ix_planning_jobs_user_uuid"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_user_id"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_status"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_session_id"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_queue_name"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_conversation_id_str"), table_name="planning_jobs")
    op.drop_index(op.f("ix_planning_jobs_conversation_id"), table_name="planning_jobs")
    op.drop_table("planning_jobs")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_table("user_profiles")
    op.drop_index("ix_conversations_user_updated", table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
