"""make_planning_job_user_id_nullable

Revision ID: 6ccb368c4300
Revises: 473363b5ea3f
Create Date: 2026-06-15 13:33:06.409801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6ccb368c4300"
down_revision: Union[str, Sequence[str], None] = "473363b5ea3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("planning_jobs", "user_id", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("planning_jobs", "user_id", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###
